### ISSUE TITLE
CLI-810: [BUG] Code studio setup command is not running from local

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#1071]
As part of https://github.com/acquia/cli/pull/873/files

We allowed to `cs:wizard` to be run from the local as well (not just cloud IDE)

but this seems not working as seems all changes are gone in refactoring.

Example - `CodeStudioCommandTrait::getGitLabHost()` and `CodeStudioCommandTrait::validateEnvironment()` - now not considering the hostname param

**Comment by anavarre** [comment]
Fixed by #1072
