### ISSUE TITLE
CLI-816: Provide the info when the IDE was created in "acli ide:info"

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#1080]
As per release notes - https://docs.acquia.com/ide/release-notes/#cloud-ide-may-1-2022
Default node version on IDE is 14

But my IDE is still showing 12 
```
node --version
v12.22.1
```

I am assuming as per https://docs.acquia.com/ide/faq/#how-can-i-tell-whether-my-ide-is-running-on-the-latest-version, to get latest apps, I need to delete and re-create the IDE.

if ^^ is correct, it would be good, if we can also expose the IDE creation date in the `acli ide:info` so that I can just check when the IDE was created.

As per https://docs.acquia.com/ide/faq/#how-can-i-audit-the-cloud-ide-lifecycle, we can get the IDE creation date but this is not intuitive (more intuitive is to get the info in ide:info command)

**Comment by anavarre** [comment]
Yes, that'd be a good addition. As a workaround you can use https://docs.acquia.com/ide/faq/#how-can-i-audit-the-cloud-ide-lifecycle

**Comment by danepowell** [comment]
This is blocked on CXAPI-9741. The Cloud API needs to provide the creation date on the ide endpoint. Parsing notification logs to infer the creation date is not feasible.
