### ISSUE TITLE
CLI-818: [Enhancement] Update "codestudio:wizard" command to support for the next-js app as well

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#1083]
Now ACMS V2 headless supports https://github.com/acquia/next-acms 
Thus CS-Wizard comment should support setup for next-js as well.

Most of the steps in `cs-wizard` command are same, except when choosing the application. In case of next-js type project, this should ask / check only for `node application`

If we check/see `acli api:applications:list` - we see `"type": "drupal",` for drupal app  and `"type": "node",` for node app.

This means - when `cs:wizard` command runs, we should ask for the app type - drupal or next-js and based on that same can be checked

(Though CS will still need a separate AutoDev Ops pipeline for next-js project)

**Comment by danepowell** [comment]
https://github.com/acquia/cli/pull/1084
