### ISSUE TITLE
CLI-839: Add additional options for cs:wizard to customize Code Studio project generation

### ISSUE THREAD

**Issue by klaw772** [acquia/cli#1142]
When creating a Code Studio project, it would be great to be able to prompt the user about their project and subsequently define/send additional AutoDevOps environment variables:

- whether the project is single-site or multi-site
- whether the Code Studio pipeline should (or should not) install Drupal as a build step

**Comment by anavarre** [comment]
Without Matt around we don't have good knowledge to help out here. Would it be possible you have someone from the Code Studio team submit a PR?

**Comment by klaw772** [comment]
@anavarre I was planning on submitting a PR for this one :) stay tuned

**Comment by danepowell** [comment]
@klaw772 is this still on your roadmap, or should we close this?

**Comment by danepowell** [comment]
I don't think @klaw772 is going to be working on this, but feel free to re-open if I'm wrong.
