### ISSUE TITLE
CLI-857: Check refresh tokens files in IDE before pulling the app

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#1177]
I'm seeing this issue when testing Cloud IDE locally. This is because ACLI's now looking for refresh token files.

```
ide:~/project $ acli pull

Warning: file_get_contents(/usr/local/share/ide/.accesstoken): Failed to open stream: No such file or directory in phar:///opt/local/acli/src/CloudApi/CloudCredentials.php on line 33

Warning: file_get_contents(/usr/local/share/ide/.expirytoken): Failed to open stream: No such file or directory in phar:///opt/local/acli/src/CloudApi/CloudCredentials.php on line 48
```

In the context of the IDE, we should likely check those files exist, then default to `acquia_cli.conf`, then fail with an authentication issue message.

**Comment by danepowell** [comment]
Catch missing files, throw as AcquiaCliException to report to bugsnag, tell users to refer to Cloud IDE known issue (@anavarre to create this)
