### ISSUE TITLE
CLI-863: The remote:aliases:download command fails with `unknown drush version` error

### ISSUE THREAD

**Issue by Tdnshah** [acquia/cli#1190]
When I run `acli remote:aliases:download` command to download latest drush aliases, I am getting an error `Unknown drush version`.

Upon investigating the above issue it was found that  in #1175 [line number 115 ](https://github.com/acquia/cli/pull/1175/files#diff-cd426bdd41a38b7df7a4ca9236f446c31b0f1410c67c6d072c5b12f8caf90cb3L115) the switch statement was updated php8's new `match()` function & as per the  [php documentation for the match](https://www.php.net/manual/en/control-structures.match.php), is an alternative to switch operation but match function `compares values strictly (===) instead of loosely as the switch statement does`. 

Hence due to this strict matching when we pass the drush version argument in the terminal the type of the version number passed is string which is getting compared by the integer which leads to fail the case and hence it default backs to the default condition which raises an error "Unknown Drush Version". 

**Steps to reproduce:**
Step 1: In local env just run `acli remote:aliases:download` in any acquia drupal project.

**Resolution:**

Lets typecast the version parameter that is getting passed to match function.

**Comment by danepowell** [comment]
Yep, good catch! Sorry about that.

**Comment by jameswilson** [comment]
This bug affects current stable release of DDEV 1.21.3 which is pinned to the current-at-time-of-release version of its upstream dependencies, in this case acli 2.5.1

Looks like this is now fixed in acli 2.5.3.

Solution approaches documented for DDEV can be found here:

https://stackoverflow.com/questions/74201310

Thanks @Tdnshah for your initial work on the PR.

**Comment by anavarre** [comment]
Linking to the merged PR for posterity https://github.com/acquia/cli/pull/1209 - It shows up in https://github.com/acquia/cli/releases/tag/2.5.2
