### ISSUE TITLE
api:environments:domains-clear-varnish not working

### ISSUE THREAD

**Issue by lnunesbr** [acquia/cli#120]
As reported on #110, api:environments:domains-clear-varnish still not working...

already using beta2 (also fails in latest HEAD on master)

```
$ acli --version
Acquia CLI v1.0.0-beta2
```

command still failing

```
acli api:environments:domains-clear-varnish 9999-999999-888888 --domains=domain1.com,domain2.com

  Too many arguments, expected arguments "command".

api:environments:domains-clear-varnish [--domains DOMAINS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command>
```

**Comment by grasmash** [comment]
I will look into this. Surprised that you’re getting this error, because the error that you should get is related to having an invalid UUID. We actually have an automated test that specifically covers this command now, so there must be something different about your environment. I will see what I can do to duplicate it.

**Comment by grasmash** [comment]
I’m actually wondering if it’s possible that the command is cached on your machine. Could you run acli cc?

**Comment by lnunesbr** [comment]
@grasmash i spun up a lando instance to run in an independent box without any cache from my local machine, and still no success.. also, cc seems to not work from the phar package (works from the cloned repo)...

```
www-data@bc2c3335a3b2:/app/beta2$ ./acli --version
Acquia CLI v1.0.0-beta2

www-data@bc2c3335a3b2:/app/beta2$ ./acli cc
PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "phar:///app/beta2/acli/var/cache/prod/annotations.map": unlink(): phar error: write operations disabled by the php.ini setting phar.readonly in phar:///app/beta2/acli/vendor/symfony/filesystem/Filesystem.php:179
Stack trace:
#0 phar:///app/beta2/acli/vendor/symfony/filesystem/Filesystem.php(173): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 phar:///app/beta2/acli/bin/acli(68): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 /app/beta2/acli(12): require('phar:///app/bet...')
#3 {main}
  thrown in phar:///app/beta2/acli/vendor/symfony/filesystem/Filesystem.php on line 179

Fatal error: Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "phar:///app/beta2/acli/var/cache/prod/annotations.map": unlink(): phar error: write operations disabled by the php.ini setting phar.readonly in phar:///app/beta2/acli/vendor/symfony/filesystem/Filesystem.php:179
Stack trace:
#0 phar:///app/beta2/acli/vendor/symfony/filesystem/Filesystem.php(173): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 phar:///app/beta2/acli/bin/acli(68): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 /app/beta2/acli(12): require('phar:///app/bet...')
#3 {main}
  thrown in phar:///app/beta2/acli/vendor/symfony/filesystem/Filesystem.php on line 179
```

Also noticed some regression with **api:applications:environment-list**

```
www-data@bc2c3335a3b2:/app/beta2$ ./acli api:applications:environment-list 81004d81-99999-999999

In Client.php line 110:

  The provided UUID '{applicationUuid}' is not a valid UUIDv4 UUID.

api:applications:environment-list [--sort SORT] [--filter FILTER] [--limit LIMIT] [--offset OFFSET] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> <applicationuuid>
```

for reference, the commands works on ADS... Same errors happens on latest git HEAD...

Thanks for assisting us with this.

**Comment by grasmash** [comment]
Thank you for being a great beta tester! Very helpful feedback.

Just adding some notes about my own testing:
```
./bin/acli api:environments:domains-clear-varnish 21351-257a5440-22c3-49d1-894d-29497a1cf3b8 --domains=eemgrasmickdev.prod.acquia-sites.com
{
    "message": "Varnish is being cleared for the selected domains.",
    "_links": {
        "self": {
            "href": "https:\/\/cloud.acquia.com\/api\/environments\/21351-257a5440-22c3-49d1-894d-29497a1cf3b8\/domains\/actions\/clear-varnish"
        },
        "notification": {
            "href": "https:\/\/cloud.acquia.com\/api\/notifications\/356f359d-6560-4cd3-8bc4-42f43fcadca7"
        }
    }
}
```

```
 ./bin/acli api:environments:domains-clear-varnish 9999-999999-888888 --domains=domain1.com,domain2.com

In Client.php line 110:

  The ID "9999-999999-888888" is not a valid environment ID.


api:environments:domains-clear-varnish [--domains DOMAINS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> <environmentId>
```

**Comment by grasmash** [comment]
Also not able to reproduce the issue with `api:applications:environment-list`:

```
./bin/acli api:applications:environment-list 81004d81-99999-999999

In Client.php line 110:

  The provided UUID '81004d81-99999-999999' is not a valid UUIDv4 UUID.
```
This is the expected output, as `81004d81-99999-999999` is not a valid UUID.

**Comment by grasmash** [comment]
Current status: I'm not able to reproduce this issue on beta2 or on HEAD. @danepowell any ideas?

**Comment by danepowell** [comment]
I haven't had time to fully investigate this, but just a few thoughts:

1. `acli cache:clear` or `acli cc` won't work for the packaged phar because the internal var cache is read-only. We might want to address that as a separate issue.
2. As a workaround to the cache clear, find your tmp dir manually (`php -r "echo sys_get_temp_dir();"`), then see if a `symfony-cache` directory exists there. If so, remove it.
3. `api:environments:domains-clear-varnish` expects an _environment id_, which is a compound key, not a simple UUID. It's a combination of the internal db id and app uuid. I think there are examples of what this should look like in the API spec. The examples in this thread seem to be using an app ID, not an environment ID.

**Comment by grasmash** [comment]
@lnunesbr Can you try running `cc` from the `master` branch and also run the command from there? This is still looking like a caching issue.

**Comment by lnunesbr** [comment]
@grasmash I found `sys_get_temp_dir()` was pointing to my OS temp directory. There was indeed a `symfony-cache/` directory in that location, I deleted it, but error remains...

Error remains using the phar (beta2), also ran cc from HEAD, but error remains as well...

```
 ~/Sites/devops/acquia/cli  master  ./bin/acli api:applications:environment-list 2cbf4649-[REDACTED]

In Client.php line 110:

  The provided UUID '{applicationUuid}' is not a valid UUIDv4 UUID.
```

I emailed you the exact UUID i am using for `api:applications:environment-list`

in regards

```
www-data@5066a0ae501c:/app$ ./acli.phar api:environments:domains-clear-varnish 2695-REDACTED --domains='domain1.io,domain2.io'
 
In Client.php line 110:
 
  The ID "{environmentId}" is not a valid environment ID.
 
 
api:environments:domains-clear-varnish [--domains DOMAINS] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> <environmentid>
```

I emailed you the exact UUIDs used (functional on ADS), so you could validate on your end.

**Comment by danepowell** [comment]
The above comment ("provided UUID '{applicationUuid}' is not a valid UUIDv4...") is definitely a bug, I can reproduce it. @grasmash I wonder if perhaps _your_ command is actually being cached here, or maybe you didn't notice the slightly different error message.

The problem is that when we build and cache the Api spec, the arguments and examples and everything are all converted to lowercase. But the path and substitution parameter are kept in camelCase, and thus never get substituted for the correct argument at runtime.

**Comment by grasmash** [comment]
🤦 my cache! Sounds right.

**Comment by grasmash** [comment]
I think I’ll just get rid of the command cache. We mostly need to cache the parsed yaml, which I added in beta2. Removing the command cache should reduce this kind of escaped defect.
