### ISSUE TITLE
CLI-872: [Improvement]  Use ACLI to push any code to acquia repo (no just drupal / composer)

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#1212]
ACLI provides command `acli push` - which prepares and deploy the artifact to the acquia git remote. This currently works with only composer based project (PHP)

So refactor this command to allow any code or artifact to push to the acquia git remote.

So someting like - one acli command to create artifact and another command to just push the artifact. This way, the second command can be used by non-drupal (nodejs) projects as well

**Comment by danepowell** [comment]
Actually, `acli push` is (or was, maybe we got rid of it) just a dummy script that reminded you to use `git push`. And `git push` is exactly how `push:artifact` pushes code.

You can already run `push:artifact --dry-run`, which builds the artifact without deploying it. So it seems like what you're really asking for is Node support for `push:artifact`?

If anything, ACLI wants to get _out_ of the business of building applications. It's only supposed to be a wrapper for Acquia products and services, it's not supposed to be tied to Drupal or specific applications. So I don't think adding support for additional application types is going to happen.
