### ISSUE TITLE
Shouldn't api commands work without uuid if it's being linked?

### ISSUE THREAD

**Issue by hanoii** [acquia/cli#123]
At least that's my assumption

**Comment by grasmash** [comment]
Good idea. We could do that.

**Comment by grasmash** [comment]
Can you give an example of a command where you'd like this automatic detection?

**Comment by hanoii** [comment]
Well, as you very well made on the last commit, the api:* were the ones that I thought initially. I didn't go over all of the commands, but basically all of those that require an UUID argument.
