### ISSUE TITLE
CLI-885: `auth:login` fails with 2FA enabled

### ISSUE THREAD

**Issue by BramDriesen** [acquia/cli#1241]
We recently enabled 2FA and "forced" this as a requirement to Access Acquia Cloud. However this also impacts the the API user which I didn't expect. We use this in our CI/CD Pipeline and so are unable to use 2FA there.

Is there a way around this?

```
+ acli auth:login --key=**** --secret=****
10:14:33  We strive to give you the best tools for development.
10:14:33  You can really help us improve by sharing anonymous performance and usage data.
10:14:33  
10:14:33   Would you like to share anonymous performance usage and data? (yes/no) [yes]:
10:14:33   > Awesome! Thank you for helping!
10:14:38  Saved credentials
10:14:38  + acli api:environments:code-switch somewebsite.dev v1.45.0
10:14:42  
10:14:42  In ExceptionListener.php line 107:
10:14:42                                                                                 
10:14:42    Cloud Platform API returned an error: This application is configured to req  
10:14:42    uire the user to have two-factor authentication enabled.
```

**Comment by danepowell** [comment]
This error is saying that the user account accessing the API does not have 2FA enabled. This is not a problem with Acquia CLI or the API itself; you'd get the same error trying the access the application through the UI.

In other words, you don't need to supply a 2FA token when working with ACLI, you just need to enable 2FA on that user account. Enabling 2FA shouldn't affect API calls.

On the off chance that it does or you are using SSO, you may need to set AH_ORGANIZATION_UUID and/or run `acli login` manually.

**Comment by BramDriesen** [comment]
Hi,

Just tried again today and you are correct 😄 enabling 2FA and configuring it on the api user solved the issue. Thnx!
