### ISSUE TITLE
CLI-887: Change IDE wizard behavior so ACLI no longer generates the SSH keypair

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#1249]
Since Cloud IDE now takes care of pre-provisioning the SSH keypair, ACLI should be simplified to no longer take care of doing this operation.

Note: for now it should still be in the business of adding the key to the keychain and SSH agent. The behavior might further be optimized in Cloud IDE overtime.

**Comment by danepowell** [comment]
Per discussion in Jira, I'd rather deprecate the entire wizard command through improvements to the IDE.
