### ISSUE TITLE
CLI-907: As a Mac user, I would like to use shell autocompletion with ZSH, as ZSH is the default shell in Mac

### ISSUE THREAD

**Issue by mayankguptadotcom** [acquia/cli#1279]
Hello I'm trying to install acli completions, however when I do that it says `Detected shell "zsh", which is not supported by Symfony shell completion (supported shells: "")`.

Is there a plan to support ZSH Autocompletion? Considering that it’s the default shell in Mac?

I also found this library that supports ZSH: https://github.com/stecman/symfony-console-completion

**Comment by danepowell** [comment]
Makes sense as a new feature. The current autocompletion is provided by Symfony itself, we didn't specifically add it. My understanding is that this is improved in Symfony 6 and especially 6.1, so maybe this problem will solve itself when we're able to upgrade.

Also it seems like Composer has autocompletion out of the box without using the stecman library, we should investigate how that works.

**Comment by danepowell** [comment]
Good news, we upgraded to Symfony 6 in https://github.com/acquia/cli/pull/1621 and I've verified that completions are now working with Zsh! https://github.com/acquia/cli/pull/1621
