### ISSUE TITLE
CLI-927: Installation of acli 2.6.2 on Ubuntu does not work (php 8.0 or php 8.1 or php 8.2) 

### ISSUE THREAD

**Issue by rajivk1636** [acquia/cli#1302]
After following the Installation steps - acli command fails

 acli
PHP Fatal error:  Uncaught GuzzleHttp\Psr7\Exception\MalformedUriException: Unable to parse URI: https:// in phar:///usr/local/bin/acli/vendor/guzzlehttp/psr7/src/Uri.php:85
Stack trace:
#0 phar:///usr/local/bin/acli/vendor/guzzlehttp/psr7/src/Utils.php(454): GuzzleHttp\Psr7\Uri->__construct()
#1 phar:///usr/local/bin/acli/vendor/guzzlehttp/guzzle/src/Client.php(67): GuzzleHttp\Psr7\Utils::uriFor()
#2 phar:///usr/local/bin/acli/src/AcsfApi/AcsfConnector.php(22): GuzzleHttp\Client->__construct()
#3 phar:///usr/local/bin/acli/src/AcsfApi/AcsfConnectorFactory.php(30): Acquia\Cli\AcsfApi\AcsfConnector->__construct()
#4 phar:///usr/local/bin/acli/src/CloudApi/ClientService.php(36): Acquia\Cli\AcsfApi\AcsfConnectorFactory->createConnector()
#5 phar:///usr/local/bin/acli/src/AcsfApi/AcsfClientService.php(19): Acquia\Cli\CloudApi\ClientService->__construct()
#6 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/getAcsfClientServiceService.php(26): Acquia\Cli\AcsfApi\AcsfClientService->__construct()
#7 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/Acquia_Cli_KernelProdContainer.php(181): ContainerIS6n4Y0\getAcsfClientServiceService::do()
#8 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/getAcsfCommandFactoryService.php(25): ContainerIS6n4Y0\Acquia_Cli_KernelProdContainer->load()
#9 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/Acquia_Cli_KernelProdContainer.php(181): ContainerIS6n4Y0\getAcsfCommandFactoryService::do()
#10 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/getAcsfApiBaseCommandService.php(20): ContainerIS6n4Y0\Acquia_Cli_KernelProdContainer->load()
#11 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/Acquia_Cli_KernelProdContainer.php(181): ContainerIS6n4Y0\getAcsfApiBaseCommandService::do()
#12 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/getApplicationService.php(35): ContainerIS6n4Y0\Acquia_Cli_KernelProdContainer->load()
#13 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/Acquia_Cli_KernelProdContainer.php(181): ContainerIS6n4Y0\getApplicationService::do()
#14 phar:///usr/local/bin/acli/vendor/symfony/dependency-injection/Container.php(215): ContainerIS6n4Y0\Acquia_Cli_KernelProdContainer->load()
#15 phar:///usr/local/bin/acli/vendor/symfony/dependency-injection/Container.php(197): Symfony\Component\DependencyInjection\Container->make()
#16 phar:///usr/local/bin/acli/bin/acli(84): Symfony\Component\DependencyInjection\Container->get()
#17 /usr/local/bin/acli(14): require('...')
#18 {main}
  thrown in phar:///usr/local/bin/acli/vendor/guzzlehttp/psr7/src/Uri.php on line 85

I tried on Php 8.0, 8.1 and 8.2 - it still fails.

I have Ubuntu 22.04 running within WSL.

Is there a Php library that needs to be installed using "sudo apt"? 

Thanks for any help..

**Comment by danepowell** [comment]
Can you post the output of `printenv | grep ACSF_FACTORY_URI` and `cat ~/.acquia/cloud_api.conf`?

The URL that Guzzle fails on comes from here, it must be invalid which would be a problem with one of these items: https://github.com/acquia/cli/blob/64ff8183e2e1834c5bef2437dde188a2f4b66045/src/AcsfApi/AcsfCredentials.php#L83

**Comment by rajivk1636** [comment]
When I invoke just "acli" command outside the project git repo, it still fails with the same error.

When I invoke it from git repo with a valid .acuia-cli.yml file - it still fails.

Here is the output of the commands you requested:

blt@REM60549L :~/Projects/tp1/$ acli
PHP Fatal error:  Uncaught GuzzleHttp\Psr7\Exception\MalformedUriException: Unable to parse URI: https:// in phar:///usr/local/bin/acli/vendor/guzzlehttp/psr7/src/Uri.php:85
Stack trace:
#0 phar:///usr/local/bin/acli/vendor/guzzlehttp/psr7/src/Utils.php(454): GuzzleHttp\Psr7\Uri->__construct()
#1 phar:///usr/local/bin/acli/vendor/guzzlehttp/guzzle/src/Client.php(67): GuzzleHttp\Psr7\Utils::uriFor()
#2 phar:///usr/local/bin/acli/src/AcsfApi/AcsfConnector.php(22): GuzzleHttp\Client->__construct()
#3 phar:///usr/local/bin/acli/src/AcsfApi/AcsfConnectorFactory.php(30): Acquia\Cli\AcsfApi\AcsfConnector->__construct()
#4 phar:///usr/local/bin/acli/src/CloudApi/ClientService.php(36): Acquia\Cli\AcsfApi\AcsfConnectorFactory->createConnector()
#5 phar:///usr/local/bin/acli/src/AcsfApi/AcsfClientService.php(19): Acquia\Cli\CloudApi\ClientService->__construct()
#6 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/getAcsfClientServiceService.php(26): Acquia\Cli\AcsfApi\AcsfClientService->__construct()
#7 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/Acquia_Cli_KernelProdContainer.php(181): ContainerIS6n4Y0\getAcsfClientServiceService::do()
#8 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/getAcsfCommandFactoryService.php(25): ContainerIS6n4Y0\Acquia_Cli_KernelProdContainer->load()
#9 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/Acquia_Cli_KernelProdContainer.php(181): ContainerIS6n4Y0\getAcsfCommandFactoryService::do()
#10 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/getAcsfApiBaseCommandService.php(20): ContainerIS6n4Y0\Acquia_Cli_KernelProdContainer->load()
#11 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/Acquia_Cli_KernelProdContainer.php(181): ContainerIS6n4Y0\getAcsfApiBaseCommandService::do()
#12 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/getApplicationService.php(35): ContainerIS6n4Y0\Acquia_Cli_KernelProdContainer->load()
#13 phar:///usr/local/bin/acli/var/cache/prod/ContainerIS6n4Y0/Acquia_Cli_KernelProdContainer.php(181): ContainerIS6n4Y0\getApplicationService::do()
#14 phar:///usr/local/bin/acli/vendor/symfony/dependency-injection/Container.php(215): ContainerIS6n4Y0\Acquia_Cli_KernelProdContainer->load()
#15 phar:///usr/local/bin/acli/vendor/symfony/dependency-injection/Container.php(197): Symfony\Component\DependencyInjection\Container->make()
#16 phar:///usr/local/bin/acli/bin/acli(84): Symfony\Component\DependencyInjection\Container->get()
#17 /usr/local/bin/acli(14): require('...')
#18 {main}
  thrown in phar:///usr/local/bin/acli/vendor/guzzlehttp/psr7/src/Uri.php on line 85
blt@REM60549L :~/Projects/tp1/$ which acli
/usr/local/bin/acli
blt@REM60549L :~/Projects/tp1/$ php -v
PHP 8.2.0 (cli) (built: Dec 10 2022 10:52:42) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.0, Copyright (c), by Zend Technologies
blt@REM60549L :~/Projects/tp1/$ printenv | grep ACSF_FACTORY_URI
blt@REM60549L :~/Projects/tp1$ cat ~/.acquia/cloud_api.conf | grep acsf_active_factory
{"send_telemetry":true,"keys":{"xxxxxx":{"label":"rk-laptop","secret":"xxxxxx"}},"acsf_factories":{"https:\/\/":{"users":{"
https:\/\/dev-xxx.acsitefactory.com":{"username":"https:\/\/dev-xxx.acsitefactory.com","key":"xxxx"}},"url":"https:\/\/","active_user":"https:\/\/dev-xxx.acsitefactory.com"}},"user":
{"uuid":"xxxxx","is_acquian":false},"acsf_active_factory":"https:\/\/"}

**Comment by danepowell** [comment]
So the problem is with your `~/.acquia/cloud_api.conf`, this has become corrupted somehow. Notice that `acsf_active_factory` is not a valid URL. Remove that key and everything should work again.

You may also need to fix `acsf_factories` where there's a bare `https://`.

**Comment by rajivk1636** [comment]
Thanks for your help - I deleted the cloud_api.conf and acli is working now. :)

**Comment by rajivk1636** [comment]
Closing the issue
