### ISSUE TITLE
CLI-960: Cannot push:artifact to default branch(master)

### ISSUE THREAD

**Issue by intercept6** [acquia/cli#1367]
When `push:artifact` is done, `git fetch` the specified branch after `git clone` is done.
By default, git fetch refuses to update the current branch(https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---update-head-ok), so `push:artifact` on the default branch (master) will cause an error.

https://github.com/acquia/cli/blob/feed53cb67ad9c6dd1fb35b858ed6a404d55e69e/src/Command/Push/PushArtifactCommand.php#L173-L182

As a result, `git checkout -b master` will be executed even though the master branch exists remotely and locally, resulting in an error.

```bash
[notice] Command: 'git' 'clone' '--depth=1' $MYREPO '/tmp/acli-push-artifact' [Exit: 0]
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository
[notice] Command: 'git' 'fetch' '--depth=1' $MYREPO 'master:master' [Exit: 128]
fatal: A branch named 'master' already exists.
[notice] Command: 'git' 'checkout' '-b' 'master' [Exit: 128]

In PushArtifactCommand.php line 193:
                                             
  [Acquia\Cli\Exception\AcquiaCliException]  
  Could not checkout master branch locally:  
                                             

Exception trace:
  at phar:///usr/local/bin/acli/src/Command/Push/PushArtifactCommand.php:193
 Acquia\Cli\Command\Push\PushArtifactCommand->cloneSourceBranch() at phar:///usr/local/bin/acli/src/Command/Push/PushArtifactCommand.php:104
 Acquia\Cli\Command\Push\PushArtifactCommand->execute() at phar:///usr/local/bin/acli/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:1058
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/acli/bin/acli:95
 require() at /usr/local/bin/acli:14
````

Perhaps this can be avoided by adding the `--update-head-ok` option to `git fetch`.
https://github.com/acquia/cli/blob/feed53cb67ad9c6dd1fb35b858ed6a404d55e69e/src/Command/Push/PushArtifactCommand.php#L177

**Comment by anavarre** [comment]
The artifact should never be stored in the `master` / `main` branch so your codebase remain clean at all times. This is the job of your CI/CD system to read your `composer.json` and `composer.lock` files to determine dependencies to be pulled to form a working version of your application that can be hosted. If you'd like to push your artifact to a branch, make it e.g. `master-build`.

What do you think is not working or what are you suggesting we do to improve the DX?

**Comment by intercept6** [comment]
Thanks, I understand the intended use.

**Comment by lems3** [comment]
> The artifact should never be stored in the `master` / `main` branch so your codebase remains clean at all times. This is the job of your CI/CD system to read your `composer.json` and `composer.lock` files to determine dependencies to be pulled to form a working version of your application that can be hosted. If you'd like to push your artifact to a branch, make it e.g. `master-build`.
> 
> What do you think is not working or what are you suggesting we do to improve the DX?

Well, right now the push-artifact CLI offers an option to push the artifact to a branch. So I would expect either the error message to be clear about the naming convention, or to allow me to push an artifact to whatever branch I want...
