### ISSUE TITLE
CLI-961: acli pull:database command when used in code studio using localhost as DB host

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#1374]
In code studio, the DB host is default to "mysql". refernce -https://code.acquia.com/acquia/standard-template/-/blob/master/gitlab-ci/Auto-DevOps.acquia.gitlab-ci.yml#L20

When this command is used in ACLI (which is being used currently), it suppose to use the mysql as host name or using the correct env variable
 
But https://github.com/acquia/cli/blob/7dacbe94d7007fdf9dab3789119c1e1064d1b7e8/src/Command/CommandBase.php#L244 it seems in order to work this with code studio, this variable has to be override.

So I think there should also be a another check for `DB_HOST` variable

**Comment by anavarre** [comment]
Yes, this is a bug in that we are opinionated towards Cloud IDE and Lando in which this value is the same. We have to abstract this out a bit more to accommodate for the Code Studio use case.

**Comment by joshirohit100** [comment]
not sure abstract way but created https://github.com/acquia/drupal-environment-detector/issues/61 if existing blt can be leveraged

**Comment by danepowell** [comment]
Is there a reason Code Studio can't set `ACLI_DB_HOST`? And for that matter, Lando should as well. Hardcoding support for Code Studio into ACLI is the kind of ugly coupling that I'm trying to get rid of.

I'd be willing to merge #1379 as a temporary fix as long as there's a ticket open to replace it with ACLI_DB_HOST on the Code Studio side later.

**Comment by joshirohit100** [comment]
Yes! In code studio, `ACLI_DB_HOST` env variable can be set by the customer. But then this will be a manual step for the customer and this means pipeline build won't work OOTB

https://code.acquia.com/acquia/standard-template/-/blob/master/gitlab-ci/Auto-DevOps.acquia.gitlab-ci.yml#L20

```
DB_HOST: mysql
```

So fix I see -

- Fix in ACLI (like we doing in the PR)
- Code studio fix the mysql host name and uses `localhost` as default (not `mysql`)

**Comment by danepowell** [comment]
Is it not possible for Code Studio to preset / hardcode `ACLI_DB_HOST`?

**Comment by danepowell** [comment]
@joshirohit100 did you see my last? Does Code Studio not set _any_ environment variables out of the box? Pretty much every CI system I've seen sets default environment variables, and ACLI_DB_HOST could be one of those.

**Comment by joshirohit100** [comment]
Yes! I have created issue in CS (and internal JIRA ticket - link in that CS issue) https://code.acquia.com/acquia/standard-template/-/issues/2

**Comment by danepowell** [comment]
I see an internal MR has been raised to set ACLI_DB_HOST, that seems like the better solution.

**Comment by rfay** [comment]
I don't think this is completed. ACLI_DB_HOST as an environment variable still doesn't work (it seems to use localhost instead?) 

In ddev:
```
export ACLI_DB_HOST=db ACLI_DB_USER=root ACLI_DB_PASSWORD=root ACLI_DB_NAME=db
$ acli pull:db ddevdemo.dev

In PullCommandBase.php line 334:

  Unable to connect to local database using credentials mysql:://root:root@db/db. ERROR 1045
  (28000): Access denied for user 'root'@'192.168.229.2' (using password: YES) 
```

Note that the IP address quoted there is *not* the IP of `db`, it's the IP address of the local container.  The IP address of `db` is `192.168.229.3` in this situation.

Note also that the reported credentials are wrong, showing two colons instead of one, `mysql:://root:root@db/db`, which may be related here.

Opened
* https://github.com/acquia/cli/issues/1629
