### ISSUE TITLE
CLI-971: Pull command is not documented

### ISSUE THREAD

**Issue by rloos289** [acquia/cli#1386]
`acli pull` is a very useful command, however it is not documented [here](https://docs.acquia.com/acquia-cli/commands/). Also, when I run `acli` in my terminal I do not see the pull command listed. This issue occurs on both the latest 1.30.1 branch and 2.8.1

I would expect to see this command listed in both places

**Comment by anavarre** [comment]
Thanks for reporting this. Clearly this is a bug because we do have plenty of arguments to document.

```
❯ acli pull --help
Description:
  Copy code, database, and files from a Cloud Platform environment

Usage:
  pull:all [options] [--] [<environmentId> [<site>]]
  refresh
  pull
  pull:all [<environmentAlias>]
  pull:all myapp.dev
  pull:all prod:myapp.dev
  pull:all 12345-abcd1234-1111-2222-3333-0e02b2c3d470
  pull:all myapp.dev default

Arguments:
  environmentId         The Cloud Platform environment ID or alias (i.e. an application and environment name optionally prefixed with the realm)
  site                  For a multisite application, the directory name of the site

Options:
      --dir=DIR         The directory containing the Drupal project to be refreshed
      --no-code         Do not refresh code from remote repository
      --no-files        Do not refresh files
      --no-databases    Do not refresh databases
      --no-scripts      Do not run any additional scripts after code and database are copied. E.g., composer install , drush cache-rebuild, etc.
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

**Comment by anavarre** [comment]
Looks like it's more complicated than I initially thought because this command is hidden by design unless you're e.g. in Cloud IDE. And it happens that we only publicly document commands that are not hidden. That's why it's not documented.

We're trying to think about the best way to go about this.

**Comment by rloos289** [comment]
I just discovered its the same case for `acli:push database` another very useful command that is hidden, but this one is actually somewhat documented [here](https://acquia.my.site.com/s/article/4413307666071-How-to-Import-push-a-local-Database-to-Cloud-IDE-or-Cloud-platform) (though not on the base acli page). 

I would argue that these kinds of commands are really core elements of building and hosting a site, and if they both function outside of the cloud IDE environment why hide them?

**Comment by danepowell** [comment]
See #1515, I agree that we can unhide these commands with some caveats / additional docs
