### ISSUE TITLE
CLI-982: Make the colors for the errors more accessible

### ISSUE THREAD

**Issue by mayankguptadotcom** [acquia/cli#1406]
<img width="925" alt="image" src="https://user-images.githubusercontent.com/8931305/224338260-2cfd08d9-42f3-47ce-830f-fe374f2c8130.png">

As we can see from the image above, it's a little hard to understand the text until I select the text. This is not an urgent requirement but it'll be nice to have the text readable. We can solve this by changing the text color to black. Please find the attached report for the accessibility color contrast check

<img width="776" alt="image" src="https://user-images.githubusercontent.com/8931305/224337939-b1889c5e-d887-4f8a-8db1-cafc68a32ca8.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/8931305/224338171-2737fd98-c562-44f6-a18d-2d90ca001b3c.png">

**Comment by danepowell** [comment]
I've never seen the color appear like that. Here's how they appear to me:

![Screenshot 2023-03-10 at 6 35 05 AM](https://user-images.githubusercontent.com/1984514/224343012-f95d3ed3-6482-4f73-b68c-fb6020e8cf4e.png)

You can see that they are much higher contrast.

We are using [standard ANSI color codes](https://ss64.com/nt/syntax-ansi.html). In the case of the background, it's 44 which corresponds to DARK_BLUE. I'd call my screenshot DARK_BLUE, but yours not so much.

What terminal are you using? Have you done something to customize the color output?

**Comment by anavarre** [comment]
I think the issue might be with the color theme you're using. I had issues like that with certain themes and I switched to one that was more standard.

**Comment by mayankguptadotcom** [comment]
I'm using iterm2 and yes it seems the color preset that I was using was the real culprit!
I changed it to a more standard color scheme and it seems all better!

<img width="878" alt="image" src="https://user-images.githubusercontent.com/8931305/224398527-669b44eb-80a4-47ca-9d81-4d2c364f4564.png">
