### ISSUE TITLE
ide:wizard:ssh-key:create-upload broken due to missing shell script

### ISSUE THREAD

**Issue by danepowell** [acquia/cli#142]
Attempting to run `ide:wizard:ssh-key:create-upload` will throw an error:
```
In IdeWizardCreateSshKeyCommand.php line 126:
  Unable to add SSH key to local SSH agent:ssh_askpass: exec(phar:///usr/local/bin/acli/src/Command/Ide/Wizard/passphrase_prompt.sh)  
  : No such file or directory
```

We thought we fixed this by including the shell script in the phar, but I confirmed it's there and we still get the error.

I think the problem is that there's simply no way to run a shell script packaged inside a phar, without doing some gymnastics: https://stackoverflow.com/questions/41710814/execute-helper-script-inside-of-phar

**Comment by grasmash** [comment]
Yikes. The script was already in a murky area of weird terminal input work aroundness. Not sure how to solve this without the script.
