### ISSUE TITLE
CLI-1087: It is possible to switch to a tag that does not exist

### ISSUE THREAD

**Issue by alberto56** [acquia/cli#1540]
**Describe the bug**

    acli api:environments:code-switch app.env tags/this-tag-does-not-exist-in-git

Then go to https://cloud.acquia.com/a/environments/MY_ENV

And you will see

![Screenshot 2023-06-12 at 8 30 21 PM](https://github.com/acquia/cli/assets/808265/941e7dd9-b882-4331-8c5a-0195975aa539)

**To Reproduce**

(1) make sure "this-tag-does-not-exist-in-git" is not a valid tag in your git repo
(2) acli api:environments:code-switch app.env tags/this-tag-does-not-exist-in-git
(3) go to https://cloud.acquia.com/a/environments/MY_ENV

**Expected behavior**

The system should refuse to switch to a non-existing tag

**Screenshots**

See above

**Desktop (please complete the following information):**

Alpine

**Smartphone (please complete the following information):**

n/a

**Comment by anavarre** [comment]
I wonder if this is by design that we'd allow doing a code switch AND creating a new tag in one go? @danepowell when you're back, could you please look into this and advise?

**Comment by anavarre** [comment]
See also #1557 @danepowell

**Comment by danepowell** [comment]
I think the bug here is actually in Cloud Platform.

`acli api:environments:code-switch` returns a notification. If you check the status of that notification, it's `failed`, which is expected for a non-existing tag.

But if you then run `acli api:environments:find` it claims your non-existent tag is checked out. In fact it's master (or your previously checked-out branch/tag, which in my case is master) that's checked out.

**Comment by cdubz** [comment]
@danepowell would that make this actually different than #1557? In my testing the notification does say the command completed even though it did not. But this was for an _existing_ tag just without the `tags/` prefix.

**Comment by danepowell** [comment]
That does sound like a slightly different bug. Let's address them both as part of this issue though. Let me make sure I've captured the two replication cases:

- If you switch code to a non-existent tag, you receive a failed task notification (as expected) and the platform reports the invalid tag as checked out in the environment (not expected)
- If you switch code to an existing tag but without the tags prefix, you received a completed notification (not expected) and the platform does not report the tag as checked out (as expected).

**Comment by danepowell** [comment]
I've reported this to the Cloud Platform engineering team. Ultimately this is an issue with the platform code checkouts; it's not something Acquia CLI can directly fix.
