### ISSUE TITLE
CLI-1088: making REST calls to Cloud IDE 

### ISSUE THREAD

**Issue by SamFoster** [acquia/cli#1541]
Hello lovely people

I realise this may be a little off topic for you, but out of desperation I thought I'd at least ask you guys....

I'm desperately trying to work out how to use POST requests to create content within my Cloud IDE instance. I can do this successfully to a DDEV based instance of my site, but there's some oauth authentication stuff i need to get past in order to do this against my Cloud IDE based Drupal instance. I can't find anything useful on the Acquia support site. If you know of a resource or can send me any CURL examples I would be very grateful. I feel it's just some header info or similar I am missing - but maybe it just isn't at all possible and I am wasting my time.

Anyhow, ANY help would be welcome.

Thanks in advance

Sam Foster
Bangor University

**Comment by anavarre** [comment]
Hello Sam,

> I'm desperately trying to work out how to use POST requests to create content within my Cloud IDE instance. I can do this successfully to a DDEV based instance of my site, but there's some oauth authentication stuff i need to get past in order to do this against my Cloud IDE based Drupal instance.

For maximum security, we proxy any request made to Cloud IDE to the Cloud Platform first so we block unauthorized access in general, but also to all Cloud Platform users but the one who created the IDE in question. Your POST requests are unauthorized and will always fail.

What you could try - as an untested workaround - is to use the `acli ide:share` command within your IDE terminal to get a unique and private share code for your IDE web URL (this is so it can be temporarily accessed by anyone, anywhere). This way you could attempt bypassing our auth system to perform POST requests.

⚠️ This is unsupported and potentially insecure if your share code leaks. Once you're done, think about regenerating the share code with `acli ide:share --regenerate`.

Good luck!
