### ISSUE TITLE
CLI-1101: Feature request: set a non-zero exit code for failed tasks using task-wait

### ISSUE THREAD

**Issue by cdubz** [acquia/cli#1556]
**Is your feature request related to a problem? Please describe.**

It appears `task-wait` always returns an exit code of `0`. When I need to wait for a command in CI it would be helpful to know (from the exit code) if the task failed so the CI run can be stopped.

Example of what happens when I try a code switch command that fails (because the tag doesn't exist):

```
> acli -nq app:task-wait "$(acli -n api:environments:code-switch "$ACQUIA_SITE_GROUP".prod "$RELEASE_TAG")"
Acquia CLI 2.12.3 is available. Run acli self-update to update.
    ✔ Waiting for task d109e8f6-bed1-4fa4-bc28-4b57f5030a36 to complete

                                                                                                                        
 [ERROR] The task with notification uuid d109e8f6-bed1-4fa4-bc28-4b57f5030a36 failed                                    
                                                                                                                        

Progress: 0
Completed: Wed Jun 28 19:43:55 UTC 2023
Task type: Code switched
Duration: 17 seconds
> echo $?
0
```

**Describe the solution you'd like**

It would be helpful if the `task-wait` command returned some non-zero exit code when the task fails.

**Describe alternatives you've considered**

I haven't tried yet but I assume for my CI use case I'll need to capture the output from the command and evaluate it for error information.

**Comment by danepowell** [comment]
Makes sense, and should be easy enough to implement: https://github.com/acquia/cli/blob/main/src/Command/App/TaskWaitCommand.php

Probably change waitForNotificationToComplete to return a bool based on success/failure. PRs welcome!
