### ISSUE TITLE
CLI-1119: api:environments:log-create does not respect date options

### ISSUE THREAD

**Issue by malcomio** [acquia/cli#1571]
**Describe the bug**
When calling `api:environments:log-create` with `from` and `to` values, those values do not affect the log file generated

**To Reproduce**
1. acli api:environments:log-create --from="2023-07-22T07:51:57+0100" --to="2023-07-23T06:51:57+0100" <environmentId> <logType>
2. wait while the log file is created
3. visit the URL provided
4. visit the download URL

**Expected behavior**
The downloaded log file should cover the date range specified

**Actual behaviour**
The downloaded log file is the same as if you had not specified a date range

**Additional context**
The `self` link shows a GET request with the from and to dates in query parameters, but the API seems to require a POST:
https://cloudapi-docs.acquia.com/#/Environments/postEnvironmentsLog

**Comment by danepowell** [comment]
@malcomio what ACLI version is this? This bug should have been fixed in Acquia CLI 2.7.0 (internal reference CLI-905)

**Comment by malcomio** [comment]
thanks - I was seeing it in 2.5.0

having updated to 2.13.0, I'm not seeing the issue any more
