### ISSUE TITLE
CLI-1171: acli throws error in Windows terminal

### ISSUE THREAD

**Issue by Jura** [acquia/cli#1610]
**Describe the bug**
Incorrect condition at https://github.com/acquia/cli/blob/23d3e326f1c695f273d2ce77eac5e3a1e702926e/src/Helpers/LocalMachineHelper.php#L226
getenv() returns null only if the respective variable is present and contains NULL as a value: https://www.php.net/manual/en/function.getenv.php . If variable doesn't exist getenv() returns FALSE instead. In that case condition currently evaluates as TRUE and substr() on the next line throws error when called as substr(FALSE, 0, 4)

**Proposed solution**
Update business logic to add additional condition to line#226:
``` 
if (getenv('MSYSTEM') !== NULL && getenv('MSYSTEM') !== false) {
```
or just
```
if (getenv('MSYSTEM'))
```

**Screenshots**
Output including error stack trace:

```
acli list -vvv

Box Requirements Checker
========================

> Using PHP 8.2.11
> PHP is using the following php.ini file:
  D:\dev\programmes\php8\php.ini

> Checking Box requirements:
  ✔ The application requires a version matching "^8.0".
  ✔ The application requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "league/csv" requires the extension "json".
  ✔ The package "m4tthumphrey/php-gitlab-api" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  ✔ The package "zumba/amplitude-php" requires the extension "json".
  ✔ The package "composer/ca-bundle" requires the extension "openssl".
  ✔ The package "composer/ca-bundle" requires the extension "pcre".
  ✔ The package "vlucas/phpdotenv" requires the extension "pcre".
  ✔ The package "m4tthumphrey/php-gitlab-api" requires the extension "xml".
  ✔ The package "marc-mabe/php-enum" requires the extension "reflection".
  ✔ The package "zumba/amplitude-php" requires the extension "curl".
  ✔ The package "laminas/laminas-servicemanager" conflicts with the extension "psr".
  ✔ The package "symfony/dependency-injection" conflicts with the extension "psr".
  ✔ The package "symfony/service-contracts" conflicts with the extension "psr".


 [OK] Your system is ready to run the application.


PHP Fatal error:  Uncaught TypeError: substr(): Argument #1 ($string) must be of type string, bool given in phar://D:/dev/programmes/cli/acli.phar/src/Helpers/LocalMachineHelper.php:227
Stack trace:
#0 phar://D:/dev/programmes/cli/acli.phar/src/Helpers/LocalMachineHelper.php(227): substr(false, 0, 4)
#1 phar://D:/dev/programmes/cli/acli.phar/bin/acli(60): Acquia\Cli\Helpers\LocalMachineHelper::getHomeDir()
#2 D:\dev\programmes\cli\acli.phar(14): require('phar://D:/dev/p...')
#3 {main}
  thrown in phar://D:/dev/programmes/cli/acli.phar/src/Helpers/LocalMachineHelper.php on line 227

Fatal error: Uncaught TypeError: substr(): Argument #1 ($string) must be of type string, bool given in phar://D:/dev/programmes/cli/acli.phar/src/Helpers/LocalMachineHelper.php:227
Stack trace:
#0 phar://D:/dev/programmes/cli/acli.phar/src/Helpers/LocalMachineHelper.php(227): substr(false, 0, 4)
#1 phar://D:/dev/programmes/cli/acli.phar/bin/acli(60): Acquia\Cli\Helpers\LocalMachineHelper::getHomeDir()
#2 D:\dev\programmes\cli\acli.phar(14): require('phar://D:/dev/p...')
#3 {main}
  thrown in phar://D:/dev/programmes/cli/acli.phar/src/Helpers/LocalMachineHelper.php on line 227
```

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by anavarre** [comment]
Could you please confirm you're on the latest version of Acquia CLI (should be 2.16.0)?

```
acli --version
```

**Comment by Jura** [comment]
I'm getting the same error on every `acli` run, including `acli --version`
![image](https://github.com/acquia/cli/assets/417604/ea8a88b7-160a-4577-83e6-8204a5f2cd2d)
But I can attest that I downloaded the most recent version (https://github.com/acquia/cli/releases/tag/2.16.0) just before I filed the bug report

**Comment by anavarre** [comment]
Thank you, that's helpful. @danepowell for awareness. Looks like https://github.com/acquia/cli/pull/1605 doesn't directly help.

**Comment by danepowell** [comment]
Thanks, this is unrelated to #1605 despite being the same environment and error class.

**Comment by danepowell** [comment]
I cannot reproduce this in Windows 11 stock versions of CMD and PowerShell because MSYSTEM is not set. How is that variable set in your environment? Are you using msys2 perhaps?

**Comment by Jura** [comment]
@danepowell , I don't have it set either, that env variable simply does not exist. Hence getenv('MSYSTEM') call returns **false** and condition `if (getenv('MSYSTEM') !== NULL) { ` effectively evaluates as **true** as it is not null but just a bool value, passing that false value to `$system = strtoupper(substr(getenv('MSYSTEM'), 0, 4));` on the next line, which throws error.

**Comment by danepowell** [comment]
Right, I can reproduce this now on vanilla CMD. I got my wires crossed, sorry for the noise!

**Comment by danepowell** [comment]
PR looks good, just needs tests (see my comment there). I also opened an upstream report, since we borrowed this code from Terminus long ago: https://github.com/pantheon-systems/terminus/pull/2509
