### ISSUE TITLE
acli ide:wizard:ssh-key:create-upload needs to run acli auth:login underneath

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#163]
Currently, we can't automate `acli` in IDEs because Acquia CLI has a different behavior than Acquia Developer Studio CLI in that it's not running the authentication command when the API keys haven't been sent.

Observe the difference below:

```
ide:~/project$ ads refresh
The refresh command requires valid Acquia Cloud credentials.
You will need an Acquia Cloud API token from <https://cloud.acquia.com/a/profile/tokens>. You should create a new token specifically for Acquia Developer Studio and get prepared to enter the associated key and secret below.
? Please enter your API Key ide:~/project$ ^C
ide:~/project$ acli refresh

In CommandBase.php line 196:
                                                                                         
  This machine is not yet authenticated with Acquia Cloud. Please run `acli auth:login`  
                                                                                         

refresh [-from|--cloud-env-uuid CLOUD-ENV-UUID] [--no-code] [--no-files] [--no-databases] [--no-scripts] [--scripts] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command>

```

So instead of quitting with an error we'd need `acli auth:login` to be executed whenever `/home/ide/.acquia/cloud_api.conf` doesn't exist.

**Comment by grasmash** [comment]
I think you're actually asking for the `acli auth:login` to be automatically run whenever a command requiring authentication is executed.

I'm not sure I want to do it. I kind of like explicitly show which command needs to be run, and I don't love wrapping commands.

**Comment by anavarre** [comment]
This is the current behavior in ADS CLI. Could we do it for IDEs at least so we can automate the API setup/SSH key generation?
