### ISSUE TITLE
CLI-1218: Access Denied Error on pull:db using ACLI 2.20.1, Drupal 10.1.5 using Lando

### ISSUE THREAD

**Issue by brooke-heaton** [acquia/cli#1634]
**Describe the bug**
I'm running ACLI inside an 'acquia' recipe Lando box using Drupal 10.1.5 and ACLI 2.20.1 and receive the following error: 

```
gzip: stdout: Broken pipe

In PullCommandBase.php line 400:
                                                                                                                                                         
Unable to import local database. ERROR 1227 (42000) at line 6654: Access denied; you need (at least one of) the SUPER privilege(s) for this operation   
```                                                                                                                      
                                  

**To Reproduce**
Create a local environment using the Lando 'acquia' recipe with acli_version set to 2.20.1, php 8.1 and drush 10.  Run the command lando acli pull:database @[site].[env] 

The command will fetch the database but fail to import the database into the local database.

**Expected behavior**
I expect the acli command to pull down a database and import it without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser N/A

**Additional context**
I AM able to direct download a DB backup from the Acquia Dashboard and use 'lando db-import' to directly import it.

**Comment by danepowell** [comment]
Would this be fixed by https://github.com/acquia/cli/issues/1629 ? i.e., dropping db tables instead of dropping and recreating the whole db.

**Comment by brooke-heaton** [comment]
Possibly @danepowell. If thre's a fix for #1629  I'd be happy tot test it out.

**Comment by brooke-heaton** [comment]
@danepowell just updating this ticket with a comment that our problem appears to not be with ACLI but an odd issue with the dynamic_entity_reference module: https://www.drupal.org/project/linkchecker/issues/3193254 

We can keep this ticket closed, but our issue was not with ACLI afternall.

**Comment by danepowell** [comment]
Wow, I never would have expected a Drupal module to be able to cause this. Thanks for reporting back.
