### ISSUE TITLE
CLI-1235: Unable to connect to local database using credentials mysql://drupal:drupal@localhost/drupal.

### ISSUE THREAD

**Issue by solomon123** [acquia/cli#1654]
**Describe the bug**
I'm using acli on lando with Acquia recipe.
All latest versions of acli after the 2.11.1, doesn't allowed me to pull:db from cloud, the following error is observed. 

```
Error message:
 **In PullCommandBase.php line 355:**   
                                                                                                                                                                                  
Unable to connect to local database using credentials mysql://drupal:drupal@localhost/drupal. ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2) 

```

**To Reproduce**
1.  configure drupal with a lando using acquia recipe
2. run `$ lando acli pull:db site.env default --no-scripts`
3. the above error will display when execution completed.

To avoid this issue, I install acli with version 2.11.1, and it work as expected.
on the latest version, no issue on pulling files and code. 

**Expected behavior**
Refresh the local database from cloud backup.

**Screenshots**
look to the screenshot attached

**Desktop (please complete the following information):**
 - OS: macOS Monterey, version 12.6
 - Browser chrome
 - Browser Version 120.0.6099.109

**Additional context**
site is configured and run puroperly by importing data manually.
I used the default db connection configuration db credential that come with Acquia recipe. 
db name: acquia
username: acquia
password: acquia

**Comment by solomon123** [comment]
I'm using lando 3.16 and docker 24.0.6, whenever I upgrade to the latest my lando and docker would not sync, for that reason I'm this stable versions. I'm using Mac

**Comment by danepowell** [comment]
I'm afraid you'll either need to upgrade Lando or downgrade Acquia CLI. Lando 3.16 is 9 months old and no longer supported (technically it's a pre-release and was never supported in the first place).

The Lando team is pretty responsive if you need help with the upgrade: https://github.com/lando/lando/issues
