### ISSUE TITLE
CLI-1267: Need help on to resolve acli auth:login  issue in azure devops

### ISSUE THREAD

**Issue by bharath0691** [acquia/cli#1680]
Hi Team,

im using acquia cli in azure devops, but when i try to login with below command getting error

command:- 
acli auth:login --key '$ACQUIA_APIKEY' --secret '$ACQUIA_APISECRET' --no-interaction -vvv

error:

 Acquia\Cli\EventListener\ExceptionListener->onConsoleError() at phar:///usr/local/bin/acli/vendor/symfony/event-dispatcher/EventDispatcher.php:260
 Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}() at phar:///usr/local/bin/acli/vendor/symfony/event-dispatcher/EventDispatcher.php:220
 Symfony\Component\EventDispatcher\EventDispatcher->callListeners() at phar:///usr/local/bin/acli/vendor/symfony/event-dispatcher/EventDispatcher.php:56
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:1087
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:320
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:174
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/acli/bin/acli:108
 require() at /usr/local/bin/acli:14

auth:login [-k|--key KEY] [-s|--secret SECRET]

 [help] Run acli auth:login to reset your API credentials.

**Comment by danepowell** [comment]
Have you omitted the actual error message from your post? I see a stacktrace but not an error message.

At any rate, assuming that command you posted is literally what you ran, I wouldn't expect it to work because you used single quotes to enclosed a Bash variable. You need to use double quotes. See https://www.gnu.org/software/bash/manual/html_node/Quoting.html

**Comment by danepowell** [comment]
Let me know if that doesn't help.
