### ISSUE TITLE
Self update command works, but displays scary error

### ISSUE THREAD

**Issue by grasmash** [acquia/cli#169]
```
 ~  Downloads  $  ./acli.phar self-update --allow-unstable
Updated from v1.0.0-beta5 to v1.0.0-beta6
;

break;
} else {
$this->addLongOption($option->getName(), null);
}
}
}




private function parseLongOption(string $token)
{
$name = substr($token, 2);

if (false !== $pos = strpos($name, '=')) {
if (0 === \strlen($value = substr($name, $pos + 1))) {
array_unshift($this->parsed, $value);
}
$this->addLongOption(substr($name, 0, $pos), $value);
} else {
$this->addLongOption($name, null);
}
}






private function parseArgument(string $token)
{
$c = \count($this->arguments);


 if ($this->definition->hasArgument($c)) {
$arg = $this->definition->getArgument($c);
$this->arguments[$arg->getName()] = $arg->isArray() ? [$token] : $token;


 } elseif ($this->definition->hasArgument($c - 1) && $this->definition->getArgument($c - 1)->isArray()) {
$arg = $this->definition->getArgument($c - 1);
$this->arguments[$arg->getName()][] = $token;


 } else {
$all = $this->definition->getArguments();
if (\count($all)) {
throw new RuntimeException(sprintf('Too many arguments, expected arguments "%s".', implode('" "', array_keys($all))));
}

throw ne
Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Event\ConsoleErrorEvent' not found in phar:///Users/matthew.grasmick/Downloads/acli.phar/vendor/symfony/console/Application.php:934
Stack trace:
#0 phar:///Users/matthew.grasmick/Downloads/acli.phar/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Acquia\Cli\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///Users/matthew.grasmick/Downloads/acli.phar/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///Users/matthew.grasmick/Downloads/acli.phar/bin/acli(101): Symfony\Component\Console\Application->run()
#3 /Users/matthew.grasmick/Downloads/acli.phar(12): require('phar:///Users/m...')
#4 {main}
  thrown in phar:///Users/matthew.grasmick/Downloads/acli.phar/vendor/symfony/console/Application.php on line 934
```

**Comment by grasmash** [comment]
This seems relevant: https://github.com/humbug/phar-updater/blob/master/README.md#avoid-post-update-file-includes

> Avoid Post Update File Includes
>
> Updating a currently running phar is made trickier since, once replaced, attempts to load files from it within a process originating from an older phar is likely to create an internal corruption of phar error. For example, if you're using Symfony Console and have created an event dispatcher for your commands, the lazy loading of some event classes will have this impact.
> 
> The solution is to disable or remove the dispatcher for your self-update command.
> 
> In general, when writing your self-update CLI commands, either pre-load any classes likely needed prior to updating, or disable their loading if not essential.

**Comment by grasmash** [comment]
Looks like the cause is...
https://github.com/acquia/cli/blob/master/bin/acli#L91-L100

**Comment by danepowell** [comment]
Right now we only use the Event Dispatcher to catch exceptions from Cloud API so it should be safe to disable as part of the self-update command... although, I don't know how to do that exactly.

Just a shot in the dark, but maybe within `UpdateCommand::execute()` add `$this->getApplication()->setDispatcher(NULL);`

**Comment by grasmash** [comment]
I'd like to move the Event Listener to a service or transform it into an Event Subscriber. https://symfony.com/doc/current/event_dispatcher.html#creating-an-event-subscriber

I can't seem to get the events to fire methods correctly.

**Comment by grasmash** [comment]
This is the quick solution: https://github.com/acquia/cli/pull/170

**Comment by grasmash** [comment]
This is still an issue, though the error is a lot less scary now:
![image](https://user-images.githubusercontent.com/539205/85349542-ba4a9700-b4cc-11ea-95d4-c6597e2fbf69.png)
