### ISSUE TITLE
CLI-1296: `auth:login` on 2.23.1 > Invalid key in Cloud datastore

### ISSUE THREAD

**Issue by alchatti** [acquia/cli#1708]
**Describe the bug**
When using the latest version of acli which is 2.23.1 the command `auth:login [-k|--key KEY] [-s|--secret SECRET]` no longer works and generates the following error.
```bash
In AuthLoginCommand.php line 31:

  Invalid key in Cloud datastore; run acli auth:logout && acli auth:login to fix

auth:login [-k|--key KEY] [-s|--secret SECRET]
```

On reverting to **2.23.0** the authentication works as expected.

**To Reproduce**
1. Update to 2.23.1 `acli self:update`
2. Login using `auth:login [-k|--key KEY] [-s|--secret SECRET]`
3. Login fails with 
    ```bash
    [Acquia\Cli\Exception\AcquiaCliException]
    Invalid key in Cloud datastore; run acli auth:logout && acli auth:login to fix
    ```
4. `acli auth:logout && acli auth:login` doesn't fix the issue.

**Expected behavior**
Login to succeed and be able to execute cli commands 

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.04.4 LTS / WSL2

**Additional context**
The Pipeline CI/CD job also fails when using the latest version and works when reverting to **2.23.0**

**Comment by anavarre** [comment]
Looks like it was introduced with #1702

**Comment by danepowell** [comment]
I cannot reproduce this issue. I tried running `acli auth:login -k <key> -s <secret>` with no cloud_api.conf, and then again immediately afterwards with the same key.

Is it possible that the error message is legitimate and your datastore (cloud_api.conf) is corrupt?

If you can't determine this on your own, you can post the contents of `~/.acquia/cloud_api.conf` or `$XDG_CONFIG_HOME/acquia/cloud_api.conf`, being sure to redact secrets, but leave enough of the key so that I can see where it's used in the file. Or you can submit this information via a support ticket.

**Comment by alchatti** [comment]
@danepowell give me couple of days to check, as I am having the issue on both my local development machine and the Azure pipeline image which resets with every job. 

It could be a PHP version issue or one of the dependencies. Will share the logs as soon as I am able.

**Comment by alchatti** [comment]
@danepowell For the CI/CD pipeline, I start with the command `acli -n telemetry:disable` then the file `~/.acquia/cloud_api.conf` will only contain the following

```json
{
    "send_telemetry": false
}
```
The following statement will be **true** [src/Command/Auth/AuthLoginCommand.php@31](https://github.com/acquia/cli/blob/0c453ac98b8bde3a713e2cc7d7efd792c798d52e/src/Command/Auth/AuthLoginCommand.php#L30C1-L30C67)
```php
if (is_array($keys) && !array_key_exists($activeKey, $keys)) {
 throw new AcquiaCliException('Invalid key in Cloud datastore; run acli auth:logout && acli auth:login to fix');
}
```

```js
is_array($keys):true
!array_key_exists($activeKey, $keys):true
```

```php
$keys = $this->datastoreCloud->get('keys');
```
Is returning array(0) although there is no keys inside the file at this stage. 
This is a side effect of setting the datastore [src/DataStore/Datastore.php#L32](https://github.com/acquia/cli/blob/0c453ac98b8bde3a713e2cc7d7efd792c798d52e/src/DataStore/Datastore.php#L32)

The issue is triggered during CI/CD pipeline by set some settings for the CLI before auth function such as switching on/off the telemetry.

I have raised a pull request if this solution doesn't conflict with the intended solution for #1702

**Comment by danepowell** [comment]
Thanks for finding the root cause here. The reason for the regression was that our tests mocked the datastore in a way that didn't exactly reflect the real behavior (keys were null instead of an empty array if unset). I've fixed all of our tests to prevent that happening again.
