### ISSUE TITLE
CLI-1404: Artifact: .gitignore file parsing issues

### ISSUE THREAD

**Issue by regilero** [acquia/cli#1800]
Hello, I'm coming to acli after the BLT EOL (https://github.com/acquia/blt/issues/4736).
We used BLT for artifact generation for ACSF and are trying to use acli for the same task.

BLT had several tools to manage the final files present in the artifact, some of them common with acli (like the sanitize steps).
But the main exclusion stuff was done via a specific `deploy-exclude.txt` list (and even hooks), and then a specific `.gitignore` file put in the final artifact (so not the same `.gitignore` file than the one used to manage the project.

Here acli is using the project main `.gitignore` file (and only this one) to perform the first copy of files and directories into the temporary working folder. Without any way to add a specific  `.gitignore` for the final artifact.
So it seems everything which is not handled by the sanitize tasks have to be excluded in this main `.gitignore` file (and we are trying to merge the blt files in this `.gitignore`).

Using this first exclusion of files before making the copy seems to work, as most project would exclude in this file the Drupal core files and all the work linked to composer. And acli would run composer in the temp directory to regenerate the missing files. This is documented as a "speed up" in the code. But I think it is also a way of excluding files from the artifact.

Our project contains folders that we want to track in git, but that we do not want in the final artifact (you can think of tests for example, or front related stuff). Not a problem, we can generate a `.gitignore` file just before the artifact generation, to fit the real exclusion list. Here a `--ignore-dirty` like in BLT would be helpful as the fact that acli wants to get a clean git status before artifact generation is a minor problem, but that's another subject.

## Problem

The problem is that in acli the parsing of this `.gitignore` is done via Symfony Finder `ignoreVCS()` function, and this function is quite bad at parsing the `.gitignore` file.

- it is only scanning one `.gitignore` file, ignoring all `.gitignore` files present in **subdirectories** or parent directories
- it **does not respect strictly the same syntax as git**, so some git silent errors or 'strange' parsing would not be treated the same way in the finder, and some invalid git syntax are valid for the Finder. I made an issue on the finder for that https://github.com/symfony/symfony/issues/58175

A simple rule like this one would fail in the finder:

```
/docroot/*
!/docroot/themes/custom
```

But this one would work for the finder:

```
/docroot/*
!/docroot/themes/custom/*
```

While being wrong for git (the leading `/*` in the exception is wrong)

I also reported issues with symlinks which may be directly related to this `ignoreVCS()` function in #1799.

It is quite simple to detect a syntax problem in a `.gitignore` file while using git, as you can see quite fast which file are tracked or not.

Finding a `.gitignore` syntax which would be compatible for both the Symfony Finder and git is really harder. And it takes a quuite long time to generate artifacts. Currently I'm still trying to find why I'm lacking some css and js files in my artifact and why I still have a `node_modules/` folder with 3 js files in it while having a clear `node_modules` line in my `.gitignore` file.

It is currently very hard to produce an artifact of the same quality than blt artifacts.

## solutions ?

I would not be surprised by a removal of `ignoreVCS()` function in the Finder some day. I would be very surprised in this function could one day parse the .gitignore file with the exact same behaviour than the latest git version.
So I think trying to only use the Finder while making the first copy of files will always be a problem.
Or at least the `ignoreVCS()` part.
One solution would be to add a deploy-exclude.txt file, with specific exclusion rules, and a syntax only valid for acli ... but that's a new file, and it breaks compatibility for people who only relies on the `.gitignore` file currently.

acli is expecting a working git directory as the starting point of the artifact generation, so another solution would be to **use git to get a very precise file list**.

This command for example:

```
git ls-files --cached --others --exclude-standard
```

Using this you get a very precise list of files that git is managing, based on the .gitignore rule (and maybe also based on the forced commit, and on files which were added before changes on the `.gitignore` files, not sure for these cases). using this would be a more clear reason of not supporting the `--ignore-dirty` mode as now the current git statut would become really important for the artifact.

This solution would lack an easy way of excluding files while still tracking them on git (like the current one), but at least we could be sure that a file not tracked by git would never be present in the artifact (with the exception of files generated after that by composer install).

**Comment by regilero** [comment]
Fun fact I was wrong on one point. The `ignoreVCS()` has evolved and it's now recursive, so it recognize `.gitignore` files that can be set in subdirectories.
This is worse for the process of making an artifact dedicated `.gitignore` file and using it just for the artifact generation, as this should be done for all `.gitignore` files in the project.

In my case the front devs added a special `.gitignore` file in the theme directory, with a valid behavior for a theme:
```
node_modules
*.css
*.js
!*.es6.js
```

Because in git you want to store pre-build stuff. But for the artifact we now have **two problems**:
- the bad parsing of exceptions in the Finder function https://github.com/symfony/symfony/issues/58175 , as here git would not even try to scan for exceptions in node_modules folder (you need `node_modules/*` in git if you want to let exceptions in the folder), but for the Symfony Finder a file like `node_modules/punycode/punycode.es6.js` would be wrongly added in the artifact
- if we generate css and js file before building thè artifact this `.gitignore` file would still prevent us from adding these files in the artifact

The main issue, I think, is things you want in git and the things you want in the artifact cannot be managed the same way. I want css and js files in the artifact, maybe not in my git.

For example you could avoid completlty the .gitignore exception when mirroring things, and remove all .gitignore files in the mirror. And then add a special .gitignore file in the artifact directory, where all artifact rules are centralized. That's what we had with BLT.
Here trying to predict the content of the artifact is a funky job.

**Comment by regilero** [comment]
interesting labelling choice. Can you explain why it's not a bug, maybe it's a feature?

**Comment by danepowell** [comment]
There's a lot going on in this request, and I'm having a hard time following exactly what it is you're asking for. It sounds like there are two issues:

1. Symfony Finder didn't behave the same as gitignore, but now you're saying that's no longer the case
2. ACLI lacks the separate gitignore or deploy-excludes mechanism for deploys

If (2) is the only remaining issue, that would make this a feature request.

If you think this is a bug, could you boil it down to "When I do x, I expect y to happen, and instead z happens?"

**Comment by regilero** [comment]
> 1. Symfony Finder didn't behave the same as gitignore, but now you're saying that's no longer the case

That's still the case. The only thing 'fixed' is that it also parse the subfolders. But this function will never respect the .gitignore syntax, there are several important issues with this function. It does not respect the exception syntax and it manages badly the symlinks. I think you should really not try to focus your artifact generation on that function, and instead use a dedicated fiile, with your own syntax.I spent a lot of hours on artifacts, really checking what was present on the end archive, and I have to maintain a special .gitignore only for the artifact, which does not respect the real .gitignore syntax. So I think there are 2 cases:

1) people are trusting the artifact generation function and ends up with strange things on the artifact
2) people have to manage a special .gitignore file for the artifact

First one is bad. Second one is the same as having to handle a dedicated artifact file.
If you think this is not a bug, fine for you.

> 2. ACLI lacks the separate gitignore or deploy-excludes mechanism for deploys

Yes, and as you can see this is linked to the fact that you rely on .gitignore parsing. I think this is not the right path for a clear artifact generation process. What I want in my git and what I want in my delivery is not related. My Drupal could even be a subtree of my git project. 

Going further.

So maybe having a default behavior which only consider simple cases is good (a git with a Drupal tree, and a simple .gitignore, no complex assets builds steps, etc.). But you need to have some ways to allow artifact generation  with finer control:

- ability to prevent .gitignore parsing
- an exclusion file to replace this .gitignore parsing
- ability to build an artifact without being in a git, or at least not requiring this git to be clean (--ignore-dirty).  Especially because the current git log is not even used on the final artifact git (so it could even work without git on the source directory)
- maybe some hooks like blt had on the final cleanup step

Currently the acli artifact looks like a regression of blt artifact, because it lacks this fine control and because it rely on a broken .gitignore parsing.

**Comment by danepowell** [comment]
The goal with the departure from BLT's separate deploy-excludes and gitignore files was to drastically simplify the artifact build for 95% of customers. For most sites, it's possible to infer what gitignored files should be forcibly added to the artifact based on composer.json (for instance, the `vendor` directory, `docroot/core`, and any scaffolded directories).

It sounds like you might have a unique case due to how your theme is set up. I'm not a frontend expert, and debugging a specific application is beyond the scope of assistance we can provide via the issue queue. I'd encourage you to reach out to your Technical Account Manager or Support with a copy of your codebase, and see if they can review this. They'd need access to your codebase, build scripts, and a precise description of what the generated artifact should look like vs what you're getting with ACLI.

**Comment by regilero** [comment]
This is not about my personal case. I made my own scripts around the issues. The .gitignore parsing is wrong, it means the artifact generation is wrong. It's a bug, a failure, the result might not be what's expected. Not just for me, I had a simple way to detect it because it could compare with the old BLT artefacts. Others might simply never see their node_modules folder is in the artifacts or  understand why  some (but not all) of the theme files are not present.

I understand that these problems coming from the Symfony component used is not making the fix an easy one. But that's certainly not something 'my Technical account manager' will fix. 

If you want to make the things simplier for 95% of the cases good. But they should be correct, so you'll have to find a way to avoid issues around the bad .gitignore parsing, where .gitignore exceptions rules are really not well parsed (and also broken symlinks management). 

You could also add options to manage the 5 other percents, as there is now no other tools to build artifacts for Acquia platforms. But that's another thing. Or just qualify these problems as requiring support, but that's not an honest move IMHO.

**Comment by regilero** [comment]
Why closing this issue?

What is completed ? I'm reporting a core defect in .gitignore parsing and artifact generation and you are talking about customer services. That's not my goal here. Can you please check the artifact generation problems?
