### ISSUE TITLE
[Feature-Request] Drush debug command

### ISSUE THREAD

**Issue by jayakrishnanj** [acquia/cli#188]
It would be really helpful if we can add `debug` mode support like Drush command `-d` for cli. verbose is very limited and i do not see much of the logs during verbose.

**Comment by grasmash** [comment]
We have -v, -vv and -vvv. I think the answer here is not to add another mode, but to add more output to one of the existing verbosity levels. What output are you looking for that is missing? We can add more output.

**Comment by grasmash** [comment]
@jayakrishnanj This issue is not actionable in its current state. Can you provide some feedback about what type of output you'd like to see?

**Comment by jayakrishnanj** [comment]
When I am trying to use any cli command, I would like to what is happening behind the screen. This is similar request like what would be shown we execute drush with`-d` 
Right now cli with `-v` is not giving complete output, example which drush config path is used. 

`ide:~/project$ cli drush st -v

In CommandBase.php line 831:
                                                                 
  [Symfony\Component\Validator\Exception\ValidatorException]     
  This value is too short. It should have 5 characters or more.  
                                                                 

Exception trace:
  at phar:///home/ide/cli/src/Command/CommandBase.php:831
 Acquia\Cli\Command\CommandBase->validateEnvironmentAlias() at phar:///h`

**Comment by grasmash** [comment]
Ok, so when `acli drush -vvv [alias] [command]` is run, we should pass `-d` to to the drush command? I'd prefer to just have the user do that with `acli drush -vvv [alias] -- [command] -d`.

**Comment by grasmash** [comment]
Given that this feature request is for a drush debug command, I'm going to close it. We already support this, you just need to change the syntax of your command slightly.
