### ISSUE TITLE
api:environments:stack-metrics-data-metric requires an additional argument

### ISSUE THREAD

**Issue by jazzslider** [acquia/cli#202]
The `help` output for the `api:environments:stack-metrics-data-metric` command suggests the following example syntax:

`acli api:environments:stack-metrics-data-metric myapp.dev web-cpu web`

Unfortunately, when I attempt that syntax (with a real site alias), I get the following error response:

```
{
    "error": "system",
    "message": "'From' date not provided."
}
```

This suggests that the underlying API call requires additional arguments to specify the date range for the data returned —but I don't see any way to provide those arguments.

**Comment by grasmash** [comment]
This seems to be an issue with Cloud API. The "from" parameter is not documented in the Cloud API specification for this endpoint. @itafroma.
