### ISSUE TITLE
ide:php-version command improvements

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#211]
The `ide:php-version` works great. I noticed a few limitations, however. See below:

* There's no indication the command was executed successfully. A better UX would be for Acquia CLI to return a) the command completed successfully and b) which PHP version is now running
* Switching to a PHP version that isn't supported works (see below when I tried to switch to PHP 8.0). A better UX would be to return this isn't available in IDEs

```
ide:~$ php -v
PHP 7.4.6 (cli) (built: Jun  1 2020 17:56:08) ( NTS )
ide:~$ acli ide:php-version 7.2
ide:~$ php -v
PHP 7.2.31 (cli) (built: Jun  1 2020 19:34:41) ( NTS )
ide:~$ acli ide:php-version 7.3
ide:~$ php -v
PHP 7.3.18 (cli) (built: Jun  1 2020 19:39:17) ( NTS )
ide:~$ acli ide:php-version 7.4
ide:~$ php -v
PHP 7.4.6 (cli) (built: Jun  1 2020 17:56:08) ( NTS )
ide:~$ acli ide:php-version 8.0
ide:~$ php -v
PHP 7.4.6 (cli) (built: Jun  1 2020 17:56:08) ( NTS )
```

**Comment by grasmash** [comment]
Fixed by https://github.com/acquia/cli/pull/210

**Comment by grasmash** [comment]
Oops! Wrong issue.

**Comment by anavarre** [comment]
Also, I just noticed https://github.com/acquia/cli/blob/ce1ae70035efe0aaed39c00228a96c7a076af3fa/src/Command/Ide/IdePhpVersionCommand.php#L89 should prevent against switching to an unknown PHP version, but I don't think it works as it should.

```
demo:/$ acli ide:php-version 8.0
demo:/$
```
