### ISSUE TITLE
Command remote:drush should accept aliases with `@` to be similar to standard drush

### ISSUE THREAD

**Issue by ba66e77** [acquia/cli#214]
I’m noticing the acli remote:drush command expects the site aliases as returned by remote:aliases:list, without the @ which is commonly used on drush aliases. If I download the same aliases through our cloud UI and use them in local drush, I’m expected to include the @. Not a big deal but kind of an annoying discrepancy. Just me?

For example, using local drush with aliases downloaded from cloud I need to run…
```
% drush @mysite.dev status
 Drupal version   : 8.8.8
....
````
With ACLI, the command is…
```
 % acli remote:drush mysite.dev status
 Drupal version   : 8.8.8
...
```

**Comment by grasmash** [comment]
See https://github.com/acquia/cli/pull/216
