### ISSUE TITLE
ide:xdebug-toggle and ide:php-version shouldn't require to be authenticated against Cloud API

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#226]
Doing this means we won't be able to test the command in IDEs to toggle Xdebug or change PHP versions because it'll require we're authenticated, which is not needed.

**Comment by danepowell** [comment]
We currently assume every command (except `auth:login` itself) requires authentication. Maybe a flag/constant on each command class is the best way to allow them to opt-in/opt-out to this requirement.
https://github.com/acquia/cli/blob/v1.0.0-rc6/src/Command/CommandBase.php#L268

**Comment by anavarre** [comment]
It's not for end users but tests, so I'm fine with any solution that would still allow us to test those commands in IDEs. I think it's an edge case we don't need to support to have users running any of those commands while not being authenticated against the Cloud Platform API.
