### ISSUE TITLE
Improve output when the user is prompted to update the PHP version in the IDE

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#232]
![cli-change-php](https://user-images.githubusercontent.com/293478/90336668-9e9bd280-dfdd-11ea-87a8-53b8237b0015.png)

Not only the formatting is off but we are returning "test" while "Stage" was selected. This is the same for Acquia, but will be confusing to our users. We should either match the user experience or use something more generic.

**Comment by anavarre** [comment]
I di

**Comment by grasmash** [comment]
As you can see in the second screenshot, the environment label is now being used. E.g., "Stage" rather than test.

**Comment by anavarre** [comment]
But the background is still not right. It should use the same color.
