### ISSUE TITLE
Create an ide:share command

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#238]
@joazvsoares to lay out the requirements

**Comment by danepowell** [comment]
Is this just supposed to return the Drupal URL + sharing code appended?

**Comment by joazvsoares** [comment]
> Is this just supposed to return the Drupal URL + sharing code appended?

@danepowell That's correct!

> Yes, something like https://example.ide.ahdev.cloud/?share=UUID

@anavarre  We need to replace the domain `ide.ahdev.cloud` to become `web.ahdev.cloud` and append the `share` query string.

**Comment by grasmash** [comment]
Are share codes already a feature? If so, should we allow an option that would regenerate the share code? E.g.,

`ide:share --regenerate`

**Comment by anavarre** [comment]
> Are share codes already a feature?

Yes. This was released as part of https://docs.acquia.com/dev-studio/ide/release-notes/#cloud-ide-september-6-2020 but not announced as we had no way for customers to interact with it, thus this ticket.

> If so, should we allow an option that would regenerate the share code? E.g., ide:share --regenerate

Yes. We wanted to do this as a follow-up but if you can find a way to make this happen in the same ticket, then that's perfect.

**Comment by anavarre** [comment]
Follow-up in #274
