### ISSUE TITLE
acli api:applications:ide-list always returns an error

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#240]
Here's an example with a sample app UUID. Tried with at leat 5 different app UUIDs for which I know there are existing IDEs.

```
$ acli api:applications:ide-list a2e88z93-a9fe-4357-b322-cdcw2da68753
{
    "error": "not_found",
    "message": "The path \"api\/api\/applications\/a2e88z93-a9fe-4357-b322-cdcw2da68753\/ides\" does not match any known resources."
}
```

It appears we’ve prepended an additional `api/` to the requested path.

**Comment by grasmash** [comment]
This appears to be a bug in the API spec: https://github.com/acquia/cli/blob/master/assets/acquia-spec.yaml#L8530

We will have to patch it and should fix it upstream.
