### ISSUE TITLE
acli api:applications:find often returns "The {applicationUuid} must be a valid UUID or site alias" error

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#241]
`acli api:applications:find <uuid>` often returns the below error while the UUID is valid:

```
In ApiCommandBase.php line 248:
                                                             
  The {applicationUuid} must be a valid UUID or site alias.  
                                                             

api:applications:find [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> <applicationUuid>
```

One potential reason for that is we're using our own UUID generation and validation compared to `typhonius/acquia-php-sdk-v2` which calls Symfony’s built in validator.

**Comment by grasmash** [comment]
We actually are using the Symfony UUID validator, Symfony\Component\Validator\Constraints\Uuid.

Can you give some examples of UUIDs that fail?

**Comment by grasmash** [comment]
@itafroma Can you suggest a better way to validate the UUIDs for Cloud API?

**Comment by itafroma** [comment]
Internally, we check to see if the UUID is 36 characters long and it matches the regexp `/^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/i`. Are there examples of UUIDs that corresponding to existing Cloud resources but are not validating with Symfony Validator?
