### ISSUE TITLE
PHP notice with acli refresh when selecting a DB

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#246]
Happening with RC7

```
PHP Notice: Undefined variable: <database> in phar:///usr/local/bin/acli/src/Command/RefreshCommand.php on line 450
```

**Comment by grasmash** [comment]
Hm. There's no $database variable on line 450 :/

**Comment by grasmash** [comment]
Oh nevermind, there was in RC7: https://github.com/acquia/cli/blob/v1.0.0-rc7/src/Command/RefreshCommand.php#L450

**Comment by grasmash** [comment]
So does the command work but it just shows this warning?

**Comment by anavarre** [comment]
Yes it works fine and shows the warning. It's really hard to catch it because it shows up and disappears almost immediately.
