### ISSUE TITLE
Regenerate parameter should modify both /usr/local/share/ide/.sharecode and /home/ide/.sharecode

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#274]
Temporarily, we're adding the share code to `/usr/local/share/ide/.sharecode` and `/home/ide/.sharecode` so we need Acquia CLI to modify it in both places for the regeneration to actually work.

@joazvsoares can expand on the details.

**Comment by grasmash** [comment]
Odd, I tested the `--regenerate` option and it did seem to work correctly.
