### ISSUE TITLE
Allow passing a sitegroup to all IDE commands

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#276]
Doing this would prevent being prompted to select an application first always, and then getting the information we need only. This would also reduce the number of web requests to the Cloud Platform API.

Here's how it looks today: 

```
$ acli ide:list
Please select a Cloud Platform application:
  [0] Corporate Site
  [1] Commerce portal
 > 0
Would you like to link the Cloud application Corporate Site to this repository? n
 ======================================================================= 
  IDEs                                                                   
 ======================================================================= 
  corpsite (foo@bar.baz)                                  
  IDE URL: https://d6l3c150-7ad7-49ff-be21-4ed45767760a.ide.ahdev.cloud  
  Web URL: https://d6l3c150-7ad7-49ff-be21-4ed45767760a.web.ahdev.cloud  
 ======================================================================= 
  portal (foo@bar.baz)                                     
  IDE URL: https://3a4a5c8c-2732-4e5c-adeb-eb3082169k91.ide.ahdev.cloud  
  Web URL: https://3a4a5c8c-2732-4e5c-adeb-eb3082169k91.web.ahdev.cloud  
 ======================================================================= 
```

Here's how it could look tomorrow:

```
$ acli ide:list portald9
Please select a Cloud Platform application:
  [0] Corporate Site
  [1] Commerce portal
 > 1
Would you like to link the Cloud application Corporate Site to this repository? n
 ======================================================================= 
  IDEs                                                                   
 ======================================================================= 
  portal (foo@bar.baz)                                     
  IDE URL: https://3a4a5c8c-2732-4e5c-adeb-eb3082169k91.ide.ahdev.cloud  
  Web URL: https://3a4a5c8c-2732-4e5c-adeb-eb3082169k91.web.ahdev.cloud  
 ======================================================================= 
```

This would apply to all commands below:

* `ide:create <sitegroup>`
* `ide:delete <sitegroup>`
* `ide:list <sitegroup>`
* `ide:open <sitegroup>`

**Comment by danepowell** [comment]
When you say "sitegroup", that's (usually) the same thing as an application / subscription right? I think we already have `cloud-app-uuid` as an option, though something more human-readable might be nice: https://github.com/acquia/cli/blob/9b7475cb56bc6a8e61306f5092601b7fce45d3cc/src/Command/CommandBase.php#L623

For many commands, you have to pick an environment in addition to an application.

Seems like we should make this consistent with how we handle aliases for api commands, which already support specifying an application and environment, and apply it to all relevant commands (not just for IDEs).

**Comment by anavarre** [comment]
> When you say "sitegroup", that's (usually) the same thing as an application / subscription right?

That's what you get with `$AH_SITE_GROUP`. It's what allows you to pass a site alias already with Acquia CLI, e.g. `sitegroup.env`.

For the commands I suggested above, we don't need to pass an environment, because for IDEs we don't care about this, it's the sitegroup only we need.
