### ISSUE TITLE
padraic/phar-updater is abandoned

### ISSUE THREAD

**Issue by danepowell** [acquia/cli#277]
On `composer install`:
> Package padraic/phar-updater is abandoned, you should avoid using it. No replacement was suggested.

I don't think this impacts end users, but obviously if this package is abandoned it could stability implications for us over time. Unfortunately I see no replacement. I doubt we want to maintain phar-updater, though that's one possible solution.

https://github.com/humbug/phar-updater/issues/59

**Comment by anavarre** [comment]
I think we should move to https://github.com/box-project/box

**Comment by danepowell** [comment]
@anavarre we actually already use Box for Phar packaging and releases :smile: The problem is it doesn't handle automated/self-updates, and my brief search revealed no alternative to humbug/phar-updater.

Maybe we can see how Drush and Composer do it.

**Comment by typhonius** [comment]
Take a look at how I do it for Acquia Cli/Logstream. I use https://github.com/consolidation/self-update and it takes care of pretty much all of the magic.

https://github.com/typhonius/acquia-logstream/blob/master/bin/logstream.php#L25

**Comment by grasmash** [comment]
Why oh why did I not discover that library in the first place?

**Comment by anavarre** [comment]
Adam "Magic" Malone. Still very much a thing in 2020.

**Comment by grasmash** [comment]
We should switch to this, but I’m hesitant to touch this feature now since it’s finally working right.

**Comment by danepowell** [comment]
I know how you feel... though the existing repo has now been not just abandoned, but archived and made read-only: https://github.com/humbug/phar-updater

So it's pretty well-and-truly dead.
