### ISSUE TITLE
Add ide:service-restart command

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#283]
To simplify operations even more, Acquia CLI should help Cloud IDE users with restarting services. At the very least, Apache, PHP and MySQL.

```
ide:~/project $ supervisorctl restart mysqld
mysqld: stopped
mysqld: started
ide:~/project $ supervisorctl restart apache2
apache2: stopped
apache2: started
ide:~/project $ supervisorctl restart php-fpm
php-fpm: stopped
php-fpm: started
```

I was wondering about how to name this command. `ide:restart` would have been great, but people might think it's about restarting the IDE. So I picked `service-restart` in the lack of anything better.

The way the command should work is this:

* `acli ide:service-restart apache` (also accept `apache2`) restarts Apache
* `acli ide:service-restart php` (also accept `php-fpm`) restarts PHP
* `acli ide:service-restart mysql` (also accept `mysqld`) restarts MySQL

**Comment by grasmash** [comment]
Why should we wrap these one liners? Seems like the acli command wouldn't actually do anything special.

**Comment by anavarre** [comment]
Because Acquia CLI would continue to be your one-stop-shop for managing IDEs. Also, because you cannot expect users to know about Linux processes (e.g. `apache2`, `mysqld`, `php-fpm`) and this new command has the potential to simplify restarting common services (e.g. restart `mysql`, not `mysqld`. Restart `php`, not `php-fpm`. Restart `apache` not `apache2`). We have a large fraction of users who come from the Windows world and don't know about Linux processes and shouldn't have to learn about them ever.
