### ISSUE TITLE
Unable to download drush 9/10 compatible sites aliaseses using remote:aliases:download

### ISSUE THREAD

**Issue by lnunesbr** [acquia/cli#300]
Couldn't find how to download drush 9/10 compatible aliases. Command `remote:aliases:download` will only download drush8 aliases.

```
$ acli --version
Acquia CLI 1.0.0
```

Using help to see if there is any options or params for the drush version, nothing:

```
$  acli help remote:aliases:download

Description:
  Download Drush aliases for the Cloud Platform

Usage:
  remote:aliases:download

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

When I run the command

```
$ acli remote:aliases:download
Cloud Platform Drush Aliases archive downloaded to /private/var/folders/ch/g5gv9f3XXXXXXXXX/T/AcquiaDrushAliasesbCHmNn.tar.gz
Cloud Platform Drush aliases installed into /Users/user/.drush
```

Only drush 8 aliases:

```
$ ls /Users/user/.drush
acapi.drush.inc					site1.aliases.drushrc.php
cache						site2.aliases.drushrc.php
cloudapi.acquia.com.pem				site3.aliases.drushrc.php

[..snip..]
```

Is it supported to download drush 9/10 aliases using acquia/cli ?

**Comment by anavarre** [comment]
FYI you can also run `acli remote:drush <sitegroup>.<env> <drush_command>` without Drush or Drush aliases installed locally.

**Comment by lnunesbr** [comment]
Thanks @anavarre , we're considering this option as well, seems promising.

**Comment by danepowell** [comment]
Cloud used to only provide Drush 8 aliases so we had no choice, but it looks like Drush 9+ versions are available now. We should probably pull those by default:
![screenshot-accounts acquia com-2020 10 09-08_05_16](https://user-images.githubusercontent.com/1984514/95599699-4219ca00-0a06-11eb-9850-4a9ed7af8771.png)
