### ISSUE TITLE
refresh and Lando

### ISSUE THREAD

**Issue by michalsen** [acquia/cli#304]
I'm quite sure this is out of scope of what you all are building, but I wanted to comment on an issue, and initial fix I found when working with a Lando local environment.

in the function importDatabaseDump() 
I set: rename($dump_filepath, 'import_sql.gz');
The reason is that Lando was adding /app/ to the file path because it can only look in its own virtual system, so I brought the file into that environment.

I then replaced the mysql command with "lando db-import import_sql.gz" as calling 'mysql' calls the system wide mysql socket, and not the socket for that specific Lando environment.

Again, I'm not putting this here as a request for change, but I wanted to document as I know I won't be the only one stuck on why 'acli refresh' breaks in a Lando env. 

Thank you

**Comment by grasmash** [comment]
This type of request seems like it’s very high value. Although, I’m worried about scope creep. There is a seemingly infinite number of different environments that we may need to support.

If we can build a way to make this easily configurable, that seems ideal. We could then let people contribute community recipes for different environments.

**Comment by michalsen** [comment]
scope creep is real, and I do not foresee what I have moved into what you all are working on. 
This is more just a side note for others that may have the same issue as me.

**Comment by grasmash** [comment]
Closing in favor of https://github.com/acquia/cli/issues/329 and https://github.com/acquia/cli/pull/331
