### ISSUE TITLE
Can't get access to stdout/stderr on remote:drush

### ISSUE THREAD

**Issue by lnunesbr** [acquia/cli#312]
Currently stumbled across a weird situation... trying to get remote:drush output via bash and assign it to a variable / and or a temp file, but can't get it via stdout and/or stderr

current acli version:

```
acli --version
Acquia CLI 1.0.0
```

When I run the command (with -vvv for verbose) sending both outputs:

```
acli -vvv remote:drush -- @site.dev status 1>/tmp/stdout 2>/tmp/stderr
 Drupal version             :  8.9.7
 Site URI                   :  http://default
 Database driver            :  mysql
[..snip..]
 Sync config path           :  profiles/site_profile/config/sync
```

I get the expected response in the first terminal (command run), but that output is not sent to my tmp files, I just get the verbose information, but not the actual command response

```
tail -f /tmp/stdout /tmp/stderr

==> /tmp/stdout <==

==> /tmp/stderr <==

==> /tmp/stdout <==

Box Requirements Checker
========================

> Using PHP 7.3.22
> PHP is using the following php.ini file:
  /usr/local/etc/php/7.3/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  ✔ The package "composer/ca-bundle" requires the extension "openssl".
  ✔ The package "padraic/humbug_get_contents" requires the extension "openssl".
  ✔ The package "composer/ca-bundle" requires the extension "pcre".


 [OK] Your system is ready to run the application.


[debug] Loading local project information...
[debug] Searching local datastore for matching project...
[debug] No matching local project found.
[debug] Searching for an environment matching alias site.dev.
[debug] Found application matching site. Searching environments...
[debug] Found environment matching dev.
```

Any idea what I might be missing here?

Running bash 3.2 on Mac catalina

```
$ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by lnunesbr** [comment]
FYI, as far as I can tell, this only happens in those **remote:drush** sub-commands

**Comment by lnunesbr** [comment]
another test here, tried sql-dump and send the output, but exact same behavior

```
acli -vvv remote:drush -- @site.dev sql-dump 1>/tmp/stdout 2>/tmp/stderr
```

While I can see the actual dump information in the command response, that is not sent to **/tmp/stdout**, only the verbose information.

**Comment by iyogesh** [comment]
A similar issue occurred in `drush` library(https://github.com/drush-ops/drush/issues/4004). [Fix](https://github.com/drush-ops/drush/issues/4004#issuecomment-500157166) mentioned there was to update 'ssh' option in the drush alias of the remote site:
```
remote:
  ssh:
    tty: 0
```

**Comment by grasmash** [comment]
I'm pretty sure the corresponding change in acquia/cli would be to remove the `t` from here https://github.com/acquia/cli/blob/master/src/Helpers/SshHelper.php#L147, although I think you'd need to do it conditionally.

**Comment by grasmash** [comment]
Actually, I confirmed that removing this line fixes it: https://github.com/acquia/cli/blob/master/src/Helpers/SshHelper.php#L83

Not sure what it might break though.

**Comment by lnunesbr** [comment]
@grasmash is it possible to have access to nightly builds so we can test this fix using the .phar package (other than cloning/composer install)? also, any idea when next stable release is coming up?

**Comment by grasmash** [comment]
We don't build phars nightly, they're only built when a tag is cut. However, you could build the phar yourself my mimicking https://github.com/acquia/cli/blob/master/.travis.yml#L36-L52

You should be able to just run `composer box-compile`
