### ISSUE TITLE
acli refresh can return duplicated databases

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#315]
I observed that under specific conditions yet to be understood, `acli refresh` can sometimes return duplicated databases in the ACSF DB array.

![acsf_duplicated-dbs](https://user-images.githubusercontent.com/293478/96416283-1d84d580-11f0-11eb-8a8c-c8e077ac2da4.png)

It doesn't happen with different ACSF subs necessarily, which makes this bug tricky to catch.

**Comment by grasmash** [comment]
Yeah I'm gonna need access to a sub where this happens.

**Comment by grasmash** [comment]
Wait ... that's not a list of databases. It looks like a list of sites from which to copy files, right?
