### ISSUE TITLE
SSH key wizard often returns duplicated info on screen

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#316]
It's been at least 3 times I've observed the same display artifact. Upon uploading the SSH key to the Cloud Platform, Acquia CLI duplicates the info on screen instead of appending.

![sshkey-repeat](https://user-images.githubusercontent.com/293478/96416620-85d3b700-11f0-11eb-95f9-deca66d849c1.png)

On screen it looks like the operation was repeated several times but it wasn't. It's just what kept showing up upon waiting.

**Comment by grasmash** [comment]
Just thinking out loud...

* It looks like only happens while the pollAcquiaCloudUntilSshSuccess() method is running
* It's possible this only occurs once the `Your SSH key is ready for use!` message is shown. Maybe this will be resolved if we remove that message
