### ISSUE TITLE
Unable to pass ssh options when running remote:drush

### ISSUE THREAD

**Issue by lnunesbr** [acquia/cli#335]
When Acquia servers are relaunched, we start get the following messages when running remote drush commands:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
```

I attempted to add `StrictHostKeyChecking no` to my `~/.ssh/config`, without success.

Considering I want to ignore those warnings, I found adding `UserKnownHostsFile=/dev/null` to my .ssh/config, it worked.

But to not consider such an invasive method to add it globally in the ssh config, or even per hosts basis, i could add ssh-options in the drush call and it worked:

```
drush @mysite.dev --ssh-options="-o UserKnownHostsFile=/dev/null" status
Warning: Permanently added 'mysitedev.ssh.prod.acquia-sites.com' (RSA) to the list of known hosts.
 Drupal version   : 9.0.7
[..snip..]
```

But I couldn't find a way to send those ssh params via acli remote:drush...

Normal acli remote drush I get the WARNING:

```
./acli.phar remote:drush -- @mysite.dev status
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
[..snip..]
```

But I couldn't find a way to add ssh-options in the acli remote:drush command

```
./acli.phar remote:drush --ssh-options="-o UserKnownHostsFile=/dev/null" -- @mysite.dev status

  The "--ssh-options" option does not exist.

remote:drush [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> <alias> [<drush_command>...]
```

Is it currently supported? How can I achieve that?

**Comment by anavarre** [comment]
I know this isn't directly answering your question, but I'd like to step back to why this message shows up to begin with. It means the SSH fingerprint has changed and you need to be informed for security purposes. If you _systematically_ shut down this message, then when something bad happens you won't know. Is this really what you want? Usually you have a one-liner to run to remove the entry from your `known_hosts` file. Is it not something you'd prefer being in control of?

**Comment by lnunesbr** [comment]
Hello @anavarre 

The fact we're using `UserKnownHostsFile=/dev/null` it means it's getting an updated host key on every call, right? So, shouldn't be an issue, as far as I see it.

And we're using this drush call in some automated scripts, and the remote host warning is breaking some steps of those scripts. I am totally open to some alternatives if you have thought in something else. Removing the knwon_hosts entry is adding a new complexity factor to these automated jobs.

**Comment by anavarre** [comment]
> So, shouldn't be an issue, as far as I see it.

It's not an issue, but I just want to make sure you're 100% okay with not being informed the SSH key fingerprint has changed.

> And we're using this drush call in some automated scripts, and the remote host warning is breaking some steps of those scripts.

I see, that's a compelling argument.

**Comment by danepowell** [comment]
This security warning exists for a reason. Granted, the signal to noise ratio is extremely low for most users, most people probably just reset the host key without thinking about it. But it still feels wrong to bypass this as a matter of course.

I think the best solution is to provide an optional argument/parameter rather than blanket ignoring this error.

**Comment by danepowell** [comment]
Discussed internally, consensus is to support `--ssh-options` argument

**Comment by danepowell** [comment]
I started to implement this but realized it could get ugly fast. For instance, should we support adding just one SSH option (`ssh -o <ssh-options>`)? Multiple options (calling `--ssh-options` multiple times)? Completely arbitrary SSH command options/arguments (`ssh <ssh-options>`)? And in any case, what about existing options that a user might want to override or remove?

Sure we can answer all of those questions and come up with an implementation, but it doesn't feel intuitive to me as an end user, and is likely to lead to more confusion and support requests.

At any rate, I think the immediate issue of changing host keys is already fixed: https://github.com/acquia/cli/blob/a478ad6936c745743bfe68168359a5be2b2b3fb7/src/Helpers/SshHelper.php#L145

If anyone wants to make additional changes, I think it's best to do so via the global SSH config (`~/.ssh/config`) or by setting/resetting the host key(s) in `~/.ssh/known_hosts`.
