### ISSUE TITLE
PHP Notice:  Undefined property: stdClass::$url in phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php on line 782

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#356]
```
[debug] Using environment Dev <REDACTED>
    ⌛ Importing Drupal database copy from the Cloud Platform...
PHP Notice:  Undefined property: stdClass::$url in phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php on line 782
[debug] Dumping MySQL database to /mnt/tmp/cfdevportal1.dev/acli-mysql-dump-dev-.sql.gz on remote server
PHP Notice:  Undefined property: stdClass::$password in phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php on line 215
PHP Notice:  Undefined property: stdClass::$user_name in phar:///usr/local/bin/acli/src/Command/Pull/PullCommandBase.php on line 215
 203 B [40.6KiB/s]
Connection to <REDACTED>.ssh.prod.acquia-sites.com closed.
[debug] Downloading database dump to /tmp/acli-mysql-dump-dev-.sql.gz
acli-mysql-dump-dev-.sql.gz
            130 100%  126.95kB/s    0:00:00 (xfr#1, to-chk=0/1)
```

**Comment by danepowell** [comment]
I've attempted to reproduce this for the given application/environment and cannot do so locally using Acquia CLI 1.1.1. I think we need more information to reproduce this.

**Comment by anavarre** [comment]
This was run from within an IDE, so Acquia CLI 1.1.1 is expected there as well https://docs.acquia.com/ide/resources/#tools

I don't have more information, this was shared from a customer failing to pull a database.

**Comment by grasmash** [comment]
I think we need to close this given there's not enough information for it to be actionable. I think it's an outdated version of ACLI given that the current version doesn't even have the line that's throwing the error.

> PullCommandBase.php on line 782

There are only 773 lines in that file today.
