### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by danepowell** [acquia/cli#367]
ACLI would likely run fine on PHP 8 if we just relax the version constraint in composer.json, but we should verify this and then change the constraint.

Currently, trying to use PHP 8 produces:
```
Box Requirements Checker
========================
> Using PHP 8.0.0
> PHP is using the following php.ini file:
  /usr/local/etc/php/8.0/php.ini
> Checking Box requirements:
  E....
 [ERROR] Your system is not ready to run the application.
Fix the following mandatory requirements:
=========================================
 * The application requires the version "^7.3" or greater.
```

**Comment by grasmash** [comment]
https://github.com/acquia/cli/pull/368

**Comment by danepowell** [comment]
May be blocked on this: https://travis-ci.community/t/php-8-0-missing/10132/15
