### ISSUE TITLE
ChoiceQuestion.php line 36:

### ISSUE THREAD

**Issue by SteeleMSU2016** [acquia/cli#388]
I am trying to create and I am getting this failure

Box Requirements Checker
========================

> Using PHP 7.3.25
> PHP is using the following php.ini file:
  /usr/local/etc/php/7.3/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                

Acquia CLI version: 1.3.0

In ChoiceQuestion.php line 36:
                                                          
  [LogicException]                                        
  Choice question must have at least 1 choice available.  
                                                          

Exception trace:
  at phar:///usr/local/bin/acli/vendor/symfony/console/Question/ChoiceQuestion.php:36
 Symfony\Component\Console\Question\ChoiceQuestion->__construct() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:494
 Acquia\Cli\Command\CommandBase->promptChooseFromObjects() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:423
 Acquia\Cli\Command\CommandBase->promptChooseApplication() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:744
 Acquia\Cli\Command\CommandBase->doDetermineCloudApplication() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:693
 Acquia\Cli\Command\CommandBase->determineCloudApplication() at phar:///usr/local/bin/acli/src/Command/Ide/IdeCreateCommand.php:55
 Acquia\Cli\Command\Ide\IdeCreateCommand->execute() at phar:///usr/local/bin/acli/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:354
 Acquia\Cli\Command\CommandBase->run() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:266
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:142
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/acli/bin/acli:88
 require() at /usr/local/bin/acli:14

**Comment by grasmash** [comment]
> I am trying to create and I am getting this failure

What are you trying to create? Can you share the exact command you're running and the full output? Also, please add the `-vvv` flag to the command.

**Comment by SteeleMSU2016** [comment]
acli ide:create -vvv

**Comment by SteeleMSU2016** [comment]
That is the output above

**Comment by SteeleMSU2016** [comment]
jasonsteele@macbook-pro ~ % acli ide:create -vvv  

Box Requirements Checker
========================

> Using PHP 7.3.25
> PHP is using the following php.ini file:
  /usr/local/etc/php/7.3/php.ini

> Checking Box requirements:
  ✔ The application requires the version "^7.3" or greater.
  ✔ The application requires the extension "json".
  ✔ The package "brick/math" requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "ramsey/uuid" requires the extension "json".
  
                                                                                
 [OK] Your system is ready to run the application.                              
                                                                                

Acquia CLI version: 1.3.0

In ChoiceQuestion.php line 36:
                                                          
  [LogicException]                                        
  Choice question must have at least 1 choice available.  
                                                          

Exception trace:
  at phar:///usr/local/bin/acli/vendor/symfony/console/Question/ChoiceQuestion.php:36
 Symfony\Component\Console\Question\ChoiceQuestion->__construct() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:494
 Acquia\Cli\Command\CommandBase->promptChooseFromObjects() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:423
 Acquia\Cli\Command\CommandBase->promptChooseApplication() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:744
 Acquia\Cli\Command\CommandBase->doDetermineCloudApplication() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:693
 Acquia\Cli\Command\CommandBase->determineCloudApplication() at phar:///usr/local/bin/acli/src/Command/Ide/IdeCreateCommand.php:55
 Acquia\Cli\Command\Ide\IdeCreateCommand->execute() at phar:///usr/local/bin/acli/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/acli/src/Command/CommandBase.php:354
 Acquia\Cli\Command\CommandBase->run() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:938
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:266
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/acli/vendor/symfony/console/Application.php:142
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/acli/bin/acli:88
 require() at /usr/local/bin/acli:14

ide:create [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> [<applicationUuid>]

**Comment by grasmash** [comment]
It looks like you may have no Cloud applications available via the CLI. Did you authenticate with Acquia Cloud via `acli auth:login`, and do you have a Cloud application?

**Comment by SteeleMSU2016** [comment]
Saved credentials to /Users/jasonsteele/.acquia/cloud_api.conf

**Comment by SteeleMSU2016** [comment]
created a second token and acli auth:login followed steps to enter new key and secret

Same failure

**Comment by grasmash** [comment]
Is it possible that you have a blt/blt.yml file? And if so, might it have an invalid application uuid in it? Perhaps try deleting it.

**Comment by grasmash** [comment]
Are you sure you have a Cloud application? The issue here is that Acquia CLI is trying to give you a list of applications to choose from, but you have 0 available Cloud applications.

**Comment by SteeleMSU2016** [comment]
ok,  guess I missed the step to create a cloud application.  I thought that was done through ide:create silly me,
Created one and actually seeing progress.  Thank you

**Comment by SteeleMSU2016** [comment]
Guess I don't have sufficient permissions.  So much for attempting this process today
