### ISSUE TITLE
Pulling files from a multisite always picks up the default directory in IDEs

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#392]
Here's an example on Acquia CLI 1.4.0 when trying to copy files from the `another` site.

* Source path is: `/mnt/files/SITENAME.ENV/sites/another/files`
* Destination path is: `/home/ide/project/docroot/sites/default/`
* Destination path should be: `/home/ide/project/docroot/sites/another/`

I checked the `sites` directory on the Cloud server, and it does indeed have an `another` directory so there's no reason why we'd pull files under `default` instead of the right location.

```
SITENAMEENV@staging-1234:/var/www/html/SITENAME.ENV/docroot/sites$ ls -l
total 24
dr-xr-s--- 2 www-data SITENAME   39 Jan  6 05:27 another
dr-xr-s--- 2 www-data SITENAME  115 Jan  6 05:27 default
-r--r----- 1 www-data SITENAME  310 Jan  6 05:27 development.services.yml
-r--r----- 1 www-data SITENAME 5749 Jan  6 05:27 example.settings.local.php
-r--r----- 1 www-data SITENAME 2363 Jan  6 05:27 example.sites.php
-r--r----- 1 www-data SITENAME  515 Jan  6 05:27 README.txt
-r--r----- 1 www-data SITENAME 2428 Jan  6 05:27 sites.php
```

Here's the full verbose debug log:

```
    ✔ Pulling code from the Cloud Platform
    ⌛ Copying Drupal's public files from the Cloud Platform...
[notice] Command: 'ssh' 'SITENAME.ENV@SITENAMEENV.ssh.prod.acquia-sites.com' '-t' '-o StrictHostKeyChecking=no' '-o AddressFamily inet' '-o LogLevel=ERROR' 'ls' '/mnt/files/SITENAME.ENV/sites' [Exit: 0]
[debug] Command:  ls /mnt/files/SITENAME.ENV/sites [Exit: 0]
 Choose a site:
  [0] another
  [1] default
 > 0
receiving incremental file list
sent 46 bytes  received 3.58K bytes  2.42K bytes/sec
total size is 1.29M  speedup is 357.35
[notice] Command: 'rsync' '-rltDvPhe' 'ssh -o StrictHostKeyChecking=no' 'SITENAME.ENV@SITENAMEENV.ssh.prod.acquia-sites.com:/mnt/files/SITENAME.ENV/sites/another/files' '/home/ide/project/docroot/sites/default/' [
    ✔ Copying Drupal's public files from the Cloud Platform
```

This should be considered high because if people push files, then they're at risk of overwriting stuff.

**Comment by danepowell** [comment]
Isn't this by design? You'd only put files in a dedicated site directory if you had a multisite setup. But IDEs don't currently support multisite, they only have a single database. Which means that whichever site is installed is the "default" site.

I'm just wondering if we move sites to a dedicated site directory, will that break existing applications or create a split-brain scenario where settings come from the default directory, but files come from a site directory.

**Comment by anavarre** [comment]
> But IDEs don't currently support multisite, they only have a single database. Which means that whichever site is installed is the "default" site.

I think there's a big nuance here: Cloud IDE supports multisite fully (you can pull your multisite codebase as well as your preferred files and database) but can only _serve_ one site at a time. We leave it up to customers to decide which site to serve at any given point in time via `sites.php`.

**Comment by SophieG** [comment]
The issue for this customer using Drupal 7 is that they have also some specific themes and modules inside the websites directories (and not in `sites/all`)

```
SITENAMEENV@staging-1234:/var/www/html/SITENAME.ENV/docroot/sites/another $ ls -lah
total 32K
dr-xr-s--- 4 www-data mega  90 Dec 18 11:55 .
dr-xr-s--- 6 www-data mega 116 Dec 18  2019 ..
lrwxrwxrwx 1 www-data mega  33 Dec 18 11:55 files -> /mnt/gfs/SITENAMEENV/sites/another/files
dr-xr-s--- 4 www-data mega  35 Sep 13  2019 modules
-r--r----- 1 www-data mega 26K Feb 11  2020 settings.php
dr-xr-s--- 6 www-data mega  92 Sep 13  2019 themes
```

... and these are not in the default directory in the IDE.

```
SITE :~/project/docroot/sites/default (master) $ ls -lah
total 64K
dr-xr-xr-x  3 ide ide 4.0K Jan  5 10:51 .
drwxr-xr-x  6 ide ide 4.0K Jan  8 08:57 ..
-rw-r--r--  1 ide ide  24K Jan  5 10:51 default.settings.php
drwxr-x--- 24 ide ide 4.0K Jan 12 09:27 files
-r--r--r--  1 ide ide  26K Jan  5 10:51 settings.php
```
