### ISSUE TITLE
Amplitude issue on Windows

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#393]
Still gathering more information, but it looks like customers can run into an issue with the Amplitude code when running Windows.

![amplitude-error](https://user-images.githubusercontent.com/293478/104421906-4f51d200-557c-11eb-87d2-ae585835f2e3.png)

**Comment by grasmash** [comment]
We really need to wrap any telemetry code in a try/catch and continue execution even when it fails.

**Comment by danepowell** [comment]
I doubt this is so much a Windows issue, and moreso an issue with the PHP curl extension being missing. Seems like Zumba should declare this dependency, and then our bootstrap code will gracefully handle it: https://github.com/zumba/amplitude-php/pull/28
