### ISSUE TITLE
acli pull environmentId option mistakenly believes the user is in an unexpected directory

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#398]
```
ide:~/project (master) $ acli pull environmentId=REDACTED_ENV_UUID

In PullCommandBase.php line 132:
                                                                
  Please run this command from the /home/ide/project directory  
                                                                
```

**Comment by danepowell** [comment]
Usage for `acli pull` is: `pull:all [--no-code] [--no-files] [--no-databases] [--no-scripts] [--] [<dir> [<environmentId>]]`

If you provide an environmentId you must also provide a directory. `acli pull . environmentId=REDACTED_ENV_UUID` should work.

I know it's not ideal but I'm not sure how to fix this. I think both `dir` and `environmentId` should be options, not arguments, but this would be a breaking change. @grasmash do you have an opinion?

**Comment by anavarre** [comment]
I didn't understand usage then. I find it very confusing we'd not abstract this out in Cloud IDE when the only dir we can pull into is `/home/ide/project`.
