### ISSUE TITLE
Store multiple Acquia Cloud tokens in local file

### ISSUE THREAD

**Issue by grasmash** [acquia/cli#399]
Given that some Acquia Cloud users have multiple Cloud accounts, Acquia CLI should store multiple  tokens and enable users to choose which is used for authentication. 

When running `acli login` provide prompt "Choose a token for login":
* [list existing tokens by label]
* Create new token

This sets the "default" token associated with all ACLI commands.

When running `acli logout`, this unsets the "default" token associated with all ACLI commands.

For each token, store:
  * Token
  * Secret
  * Label
  * Anything else that would be valuable.

**Comment by danepowell** [comment]
@grasmash what's the practical benefit to users here? The only use case I can imagine is to use multiple Cloud accounts, and I can't imagine that's common. It's also not something that I'm aware of similar CLIs supporting.

**Comment by grasmash** [comment]
The practical benefit is that users with more than one Cloud account can easily use Acquia CLI.

Two data points:
* Our Lando Plugin will use Acquia CLI. Lando has an existing pattern for using multiple tokens to support this use case.
* I pinged our PS team to see if this would be valuable. They validated that this would be valuable for employees and partners.

**Comment by grasmash** [comment]
Here's an example of the Lando interface:
![image](https://user-images.githubusercontent.com/539205/106302429-f8f4bc80-6226-11eb-8042-0cb627a9bdfc.png)

**Comment by danepowell** [comment]
I've just never heard of anyone having more than one Cloud account... and why would they, since the Teams system allows you to be on any number of teams at once. But I guess if people are asking for it, we can consider it 🤷
