### ISSUE TITLE
Add 'validate-codebase' command

### ISSUE THREAD

**Issue by grasmash** [acquia/cli#406]
This is just a blue sky idea.

We could add a `acli validate-codebase` command that validate that:
* composer.json is at the root
* a docroot subdirectory exists
* docroot/sites/default/settings.php contains the acquia require line

**Comment by anavarre** [comment]
Looks like `acli audit` to me. Also, what about D7 VS D8+?

**Comment by danepowell** [comment]
This veers dangerously close to coupling ACLI to particular Drupal versions, or even to Drupal/Composer generally. We've tried to keep it application-agnostic thus far.

What's the use case here? Who's asking for this, and how would it benefit people?
