### ISSUE TITLE
Auth:login doesn't refresh tokens

### ISSUE THREAD

**Issue by vitaly-malashevsky** [acquia/cli#421]
Working with the acquia cloud api causes the token to expire time to time or become invalid due to unknown reasons. For example:  

1. create a fresh token in Acquia
2. run auth:login using the token
3. try several commands to ruin the token eg: `acli api:applications:artifact-list appid --sort="created" --filter='name=@*hash' --limit="3"`

Until you see this message:
```
$ acli api:applications:artifact-list

In ExceptionListener.php line 34:
                                                                                       
  Your Cloud Platform API credentials are invalid. Run acli auth:login to reset them.  
                                                                                       

api:applications:artifact-list [--sort SORT] [--filter FILTER] [--limit LIMIT] [--offset OFFSET] [--] <applicationUuid>
```

Running the proposed command and reusing the stored token doesn't solve the problem. Any command fails with the same error.
![image](https://user-images.githubusercontent.com/8169225/108827026-bdeb6c00-75cd-11eb-8957-f745ca92c107.png)

The only thing that helps is this magic command: `rm -f ~/.acquia/cloud_api.conf` or a new token generated and used.

**Comment by anavarre** [comment]
Which version are you using (`acli --version`)? We're going to release a new version (1.7.0) with #413 and #404 that should fix auth regressions we've been made aware of.

Could you please pass `-vvv` for commands that are failing, too, so we have a backtrace?

**Comment by vitaly-malashevsky** [comment]
```
docker@cli:/var/www$ acli --version
Acquia CLI 1.6.0
```
Played with the verbosity flags and found nothing useful in there. Don't have those traces at the moment. Once got, will provide.

**Comment by anavarre** [comment]
Thanks @vitaly-malashevsky - Could you please try to update (`acli self-update`) to 1.7.0 and let us know whether it works better for you now? https://github.com/acquia/cli/releases/tag/1.7.0

**Comment by vitaly-malashevsky** [comment]
@anavarre I'm no longer able to reproduce the issue with the updated acli version. Seems, it been solved by https://github.com/acquia/cli/pull/404 Thanks a lot.
