### ISSUE TITLE
Notice: Trying to get property 'sshUrl' of non-object in phar://opt/local/acli/src/Helpers/SshHelper.php on line 158

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#424]
User ran into the following error message when clicking on the IDE "Configure IDE" button in a brand new IDE

```
Notice: Trying to get property 'sshUrl' of non-object in phar://opt/local/acli/src/Helpers/SshHelper.php on line 158
```

Never ran into this. This is happening with 1.5.0 (asked the user to update to 1.7.0 and report back)

**Comment by danepowell** [comment]
It would help to get the full stack trace, since the SSH Helper is called from many other parts of Acquia CLI. It accepts the environment as a parameter and that's what's `null` here, something must be feeding it an invalid environment.

I suspect it's still a valid bug but I don't know how to reproduce.

Possibly related: https://github.com/acquia/cli/issues/228

**Comment by anavarre** [comment]
Asked for a backtrace. Hopefully we get it soon

**Comment by anavarre** [comment]
Didn't get a trace because upon running the command in verbose debug, generating and uploading the key worked. So we know it fails only the first time, which is good for the user, but not so good for us to reproduce.

<img width="477" alt="new-attempt" src="https://user-images.githubusercontent.com/293478/109162047-0b0b4180-7778-11eb-8cc3-31c97a50107f.png">

**Comment by grasmash** [comment]
So... the selected environment somehow isn't "grabbed" via the the API correctly. I'd expect this has to do with the application or environment being a bit unusual.

**Comment by danepowell** [comment]
Good point. I've seen subscriptions with zero environments and other oddities before. But without knowing the specific environment, it's hard to say.

**Comment by danepowell** [comment]
I collaborated with Aurelien via Slack, I found that the application in question lacks a Dev environment, and we hardcode a polling function on the dev environment: https://github.com/acquia/cli/blob/b0cddb2b887292a4e9323983a0180e7d1e2c10e5/src/Command/Ide/Wizard/IdeWizardCreateSshKeyCommand.php#L268

We need to have a fallback there in case the dev environment doesn't exist. Unfortunately there's no single environment that we can guarantee to exist on every sub.

**Comment by anavarre** [comment]
Should we fallback to having `getProdEnvironment` in case `getDevEnvironment` doesn't work?
