### ISSUE TITLE
acli new returns an error downloading the project from dist in Cloud IDE

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#426]
<img width="840" alt="acli-new-from-dist" src="https://user-images.githubusercontent.com/293478/109014952-e9955180-76b4-11eb-944b-0f6e7706be00.png">

**Comment by grasmash** [comment]
Seems like this may be a bug in Composer or in the acquia/drupal-minimal project.

**Comment by grasmash** [comment]
But ... this does not seem critical. It looks like it fell back to downloading from source. 

I think the issue here is more that there is no release of acquia/drupal-minimal-project.

Is this worth fixing?

**Comment by danepowell** [comment]
Yeah, it's completely normal for Composer to fall back to source for any number of reasons: network issues, rate limiting, version constraints... It's not something we should treat as an error or try to remediate.

Having said that: wth is happening here? `//vendor/composer does not exist and could not be created`

@anavarre this indicates a problem with your local environment, do you have weird file permissions or symlinks in your project directory or something? Can you recreate this consistently?

**Comment by anavarre** [comment]
Confirmed with Matt that was a network issue :shrug: 

> do you have weird file permissions or symlinks in your project directory or something?

No, that was under `/home/ide/project` in a new IDE.
