### ISSUE TITLE
Make it obvious you can pass a sitegroup.env every time you can pass an environment ID

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#431]
It’s becoming increasingly obvious that we need to make this very clear to users. It’s in the help documentation for each command, but it seems like almost everybody misses it. We should likely return it when the command fails as well.

**Comment by danepowell** [comment]
I would consider this closed by https://github.com/acquia/cli/pull/429

I can't imagine where else people are being misled. Environment IDs aren't exactly intuitive (certainly no more intuitive than aliases), so if people are using env ids it must be because they were _told_ to use env ids. And #429 covers the only places I know of that being the case.

**Comment by anavarre** [comment]
Sorry, IDK how #429 helps. Could you please help me understand? To give you an example, here's what I get against `master`.

```
$ ./bin/acli api:environments:domain-list

                                                    
  Not enough arguments (missing: "environmentId").  
                                                    

api:environments:domain-list [--sort SORT] [--filter FILTER] [--limit LIMIT] [--offset OFFSET] [--] <environmentId>
```

But what I would expect here is this:

```
$ ./bin/acli api:environments:domain-list

                                                    
  Not enough arguments (missing: "environmentId").  
                                  

api:environments:domain-list [--sort SORT] [--filter FILTER] [--limit LIMIT] [--offset OFFSET] [--] <environmentId>

Note: "environmentId" can also be sitegroup and environment construct, e.g. myapp.dev              
```

**Comment by grasmash** [comment]
#429 Updates the help text for each command to indicate that an alias can be used.

**Comment by anavarre** [comment]
This is assuming people will run the command that just failed with `--help`. This is not often the case. People are stuck.

**Comment by danepowell** [comment]
Well that answers my question about "where are people being misled". Yeah, we can rewrite that API exception. Looks like Matt is already on it.
