### ISSUE TITLE
Override the spec to better set expectations when an IDE is going to be deleted

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#434]
Right now, when deleting an IDE, we return the deletion message from the spec:

> The Cloud IDE is being deleted.

It gets users confused, because K8s takes a few minutes before actually processing the deletion. We should override the message and better set expectations. Here's a suggestion:

> The Cloud IDE will be deleted momentarily. This process usually takes a few minutes.

**Comment by grasmash** [comment]
@anavarre We should really change the message it Cloud API / HAPI.

**Comment by danepowell** [comment]
I agree, this is turning into an anti-pattern. We should focus our effort on fixing things like this upstream rather than maintaining an endless string of overrides (hacks, really).

**Comment by anavarre** [comment]
PR field upstream but we can't guarantee a quick turnaround time.
