### ISSUE TITLE
Users are confused with api sub-commands placed halfway through the acli output and too many commands in general

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#435]
Right now, when typing `acli`, users miss that we have way more API commands available, despite the cyan color. This is because the below is shown ~halfway through the output:

```
 api
  api:accounts:find                        Returns details about your account.
  api:environments:code-deploy             Deploys code to this environment.
  api:environments:database-backup-create  Create a backup.
  api:environments:domain-clear-varnish    Clears the Varnish cache for the specified domain.
  api:list                                 [api] There are more hidden API commands! Run api:list to see them all.
```

It's also confusing to them what the `api` grouping really means and they find we have many commands on screen.

-----

We could explore several improvements:

1. Place `api:*` sub-commands at the very end of the `acli` output so they'd stand out immediately (but then we'd lose the A-Z ordering)
2. Only show `api:list` with a even more descriptive message, without suggesting common commands we assume would be most helpful for a large fraction of our users

Perhaps it's a "not a bug, won't fix, but let's explore whether there's anything we can think of.

**Comment by grasmash** [comment]
Another idea, only show top level command groups. E.g., have commands for:

```
api:accounts:*                Display all API commands for accounts.
api:agreements:*              Display all API commands for agreements.
api:applications:*            Display all API commands for applications.
api:environments:*            Display all API commands for environments.
api:ide:*                     Display all API commands for IDEs.
api:identity-providers:*      Display all API commands for identity providers.
...
```

**Comment by anavarre** [comment]
Could work but sometimes we'll have only one occurrence, e.g. `api:notifications:find`

**Comment by grasmash** [comment]
> Could work but sometimes we'll have only one occurrence, e.g. api:notifications:find

We can skip those occurrences.
