### ISSUE TITLE
Only allow self-update to run when we detect the target Phar exists

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#438]
Would have prevented #437

**Comment by grasmash** [comment]
Needs to be fixed upstream, see https://github.com/consolidation/self-update/issues/7

**Comment by grasmash** [comment]
Depends on https://github.com/danepowell/self-update/pull/2 now

**Comment by grasmash** [comment]
This will be resolved https://github.com/acquia/cli/pull/456, which includes an update to the consolidation/self-update library.
