### ISSUE TITLE
Better set expectations when an IDE is going to be available

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#445]
We have IDE pre-provisioning that is going to soon be available. Now, instead of creating an IDE and waiting for DNS propagation, we're going to claim a pre-provisioned IDE and wait for it to be configured.

We should thus change the message to indicate the IDE is being configured, rather than waiting for DNS propagation. More importantly, we should indicate this process usually takes between 5 and 15 minutes.

**Comment by grasmash** [comment]
Might be a bit confusing when the customers finally get the IDE, login, read the instructions, and see that the first step is to click “Configure IDE.”

**Comment by anavarre** [comment]
That's a good point. Can't really think of a better verb, though. Perhaps "prepared" could work?

**Comment by anavarre** [comment]
Actually, used "ready" which works well I think.
