### ISSUE TITLE
Black text on dark blue background doesn't work for Mac users with the default white Terminal

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#464]
Participated in user session in which black on dark blue was basically unreadable. This is the new help block we have just introduced.

We need to come up with better contrast for all terminals, whether white or black, or any shade of that. Perhaps there's an industry standard we can follow?

**Comment by grasmash** [comment]
![image](https://user-images.githubusercontent.com/539205/110353227-d1062f00-8004-11eb-9a4e-ccc65420a364.png)

**Comment by grasmash** [comment]
![image](https://user-images.githubusercontent.com/539205/110353298-e4b19580-8004-11eb-9155-45ee394d5342.png)

**Comment by pratikpp** [comment]
the Test on blue is unreadable. if the background is blue, the text should be white

**Comment by anavarre** [comment]
See #466
