### ISSUE TITLE
Acquia CLI tries to pull the files directory even when no files directory exists yet

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#472]
Found with user testing. Acquia CLI returns the following when no Drupal site is installed on the Cloud Platform:

```
Choose a site
> [0]
```

The user is forced to select `0` and then Acquia CLI fails with an error because there's no source files directory to copy from. We'd need to find a way to abort before we get to the error.

**Comment by anavarre** [comment]
Probably the same issue happens with the DB as well. We should exit early.

**Comment by grasmash** [comment]
How does this even happen? Why would there be no default or other site directory?

**Comment by anavarre** [comment]
That's the thing. There's none. Think about a new application that just got provisioned, but there's nothing actually installed _yet_. Customers still can be confused and try to pull the app into the IDE. It will have the base repo with default files, but no DB and files.

**Comment by grasmash** [comment]
Yes but doesn’t the base repository still have a sites/default directory ?

**Comment by anavarre** [comment]
No, the base repo only has this layout for `docroot`

```
.htaccess
acquialogo.gif
index.html
```
