### ISSUE TITLE
Importing a DB into Cloud IDE can be memory intensive

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#493]
In `/src/Command/Pull/PullCommandBase.php` we have a command to download and import a database.

```
"pv $local_dump_filepath --bytes --rate | gunzip | MYSQL_PWD=$db_password mysql --host=$db_host --user=$db_user $db_name";
```

This operation can have Cloud IDE running out of memory.

```
Choose a Cloud Platform environment:

[0] Dev, dev (vcs: feature-translation-updates)
[1] Dev2, dev2 (vcs: feature-industrial-redesign)
[2] Prod, prod (vcs: tags/2021-03-16.0)
[3] Stage, test (vcs: master)

> 0

[debug] Using environment Dev 29187-bk1618b0-abc8-4115-b62w-775b215ca8ad
⌛ Importing Drupal database copy from the Cloud Platform...

[debug] Using database backup generated at 2021-03-17T10:01:18+00:00

[debug] Downloading database backup to /tmp/backup-2021-03-17T10:01:18+00:00-myapp.sql.gz

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 545015592 bytes) in phar:///opt/local/acli/vendor/guzzlehttp/psr7/src/Stream.php on line 95
```

Not sure how to make this less memory intensive. It's possible that splitting this into 2 commands would be better. E.g., first unzip, then import in a separate command.

**Comment by danepowell** [comment]
I suspect the memory usage is not from the db import (which uses Unix pipes, the input should be entirely buffered with minimal memory usage). I suspect it's actually due to the db dump loading the file contents into the PHP process.
