### ISSUE TITLE
[push:files] cannot select environment

### ISSUE THREAD

**Issue by danepowell** [acquia/cli#509]
When running push:files, selecting anything other than the default target environment produces PHP notices and a fatal error.

I think the problem has to do with the `$allow_production` parameter in `determineEnvironment()` and how the list of environments is modified to remove prod.

**Comment by grasmash** [comment]
I can't reproduce this.

**Comment by danepowell** [comment]
@grasmash I can still reproduce on HEAD. I sent you the name of an application, try running `push:files`, select that application, then select the stage environment. The default environment is dev and that works fine, the error only occurs if you select a non-default environment.

**Comment by danepowell** [comment]
Fixed in #526 

This occurs when Cloud API returns environments "out of order", i.e. `[0] => dev, [1] => prod, [2] => stage`.

Then when `determineEnvironment()` unsets prod, you're left with `[0] => dev, [2] => stage`, and those keys won't match what's in choices (i.e. `1` is missing).
