### ISSUE TITLE
telemetry command should not be toggle

### ISSUE THREAD

**Issue by shelane** [acquia/cli#511]
I need to reliably set the telemetry command to disabled for non-interactive scripts. In BLT, I can run `blt blt:telemetry:disable` and know that it will be disabled. Otherwise, I could accidentally turn it on. This is what I want to do:

```
acli api:environments:domain-create ${env_prod}-${appid} --hostname="${name}" -n | jq '.message'
```

But if telemetry is on, I can get this error:
```
parse error: Invalid numeric literal at line 1, column 3
```
And my script stops. You would think that the -n flag would be enough, but it doesn't seem to be.

**Comment by grasmash** [comment]
Would it resolve your issue if we added the following commands?

* acli telemetry:enable
* acli telemetry:disable

**Comment by shelane** [comment]
Yes. That would make it consistent so I can just set it to disable at the beginning of my script.
