### ISSUE TITLE
Git cmdline and IDE are confused about each other

### ISSUE THREAD

**Issue by SamFoster** [acquia/cli#524]
Hello again guys!

So I have worked through @anavarre 's helpful feedback re connecting the GIT remote etc and I have a call in with Acquia support on Monday. I decided to start my project again and see how much further I could get

Well, I kinda got a little further before I started experiencing my next issue - hence this ticket

Again, I'm on Win 10.

In the IDE I see mismatch between what the GUI thinks I'm working on, and what the GIT cmd line thinks. Basically, they think i'm on different branches!
** edit ** i think Ive just been a victim of poor performance issues (prob network related?) - as now as go back to get you some screenshots I see it switching between branches takes about 3 seconds to have the GUI reflect what I do in the terminal with a git checkout)

anyway - a further funny of the same type is that whilst I can pull/push with the cmd line - it fails when I use the options in the GUI - for example a PUSH using the GUI results in 

---snip
Request push failed with message: Authentication failed. You may not have permission to access the repository or the repository may have been archived.
--snip

![git5](https://user-images.githubusercontent.com/635728/115054948-c29b1500-9ed8-11eb-8eb9-3788a3f5f5fb.jpg)

but, if I do a push in terminal is succeeds.

What's not working?

(probably me!)

Sam

**Comment by anavarre** [comment]
The Git UI authentication failed notification you're seeing is a known Cloud IDE issue we're working on resolving after we upgrade Theia (the UI) to its latest version.

I don't see any Acquia CLI issue in your report so I'm going to close this out. Please continue working with Acquia Support on any IDE challenge you encounter.

Thanks!

**Comment by SamFoster** [comment]
Has there been a fix for this yet. Ive done a self-update to version 1.13.1 but I still dont see code changes reflected in the GUI, or even see the same branches listed in the gui drop down as I do if I use cmd line 'git branch -r' or even 'git branch'

Am I doing something wrong ? Is my acli instance mis-configured or does this just not work yet? Can I update Theia manually if that is the issue?
