### ISSUE TITLE
Windows users are often seeing color codes instead of actual colors

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#532]
I keep on seeing this happening at least 50% of the time I'm helping a customer on Windows

![windows-colors](https://user-images.githubusercontent.com/293478/116542685-367fe900-a8ed-11eb-81b4-ddebad03e3b9.png)

**Comment by grasmash** [comment]
Is it always following a prompt?

**Comment by grasmash** [comment]
Looks a lot like this: https://github.com/symfony/symfony/issues/37155

**Comment by anavarre** [comment]
> Is it always following a prompt?

Seems like it but I cannot say for sure since I have only failed operations that are reported, and they usually involve a prompt.

**Comment by grasmash** [comment]
I think we should close this as won’t fix. This is an upstream problem in Symfony console and I doubt that we will tackle it ourselves.
