### ISSUE TITLE
Check disk space left before allowing archive:export to run

### ISSUE THREAD

**Issue by anavarre** [acquia/cli#548]
The new `archive:export` command is great, but in case it fills up the disk, users might be running into issues with the IDE. We should prevent this from happening by first:

* Checking the DB size on disk
* Checking the repo size (with files) on disk
* If and only if the total amount (with a compression factor) does not exceed the IDE disk size, run operations

**Comment by grasmash** [comment]
Eh. This is bit tricky. It's going to be an estimate at best. 

Where is the DB on disk?

**Comment by anavarre** [comment]
The `drupal` DB is located under `/home/ide/mysql-data/drupal`. If we `du -h` on disk we will get the human readable size. The equivalent PHP way will give us an indication of the total DB size and codebase/files size.

Agreed it's tricky to get the compression factor right. For example compression MySQL data works great, but we know assets will not be correctly compressed. So what I could suggest is this:

**MySQL**

Consider at least a 90% decrease as shared here https://serverfault.com/a/484659/201731 and observed just now on a test IDE:

```
test:~/project (master *) $ drush sql-dump > /tmp/dump.sql.gz
test:~/project (master *) $ cd /tmp/
test:/tmp $ du -h dump.sql.gz 
5.4M    dump.sql.gz
```

**Codebase/files**

Consider a 5% decrease, maybe?

**Comment by danepowell** [comment]
I don't think this is feasible. One hard lesson we've learned is that it's almost impossible to predict and prevent resource exhaustion. I have no interest in attempting it again.

There are a lot of ways to exhaust resources beyond disk usage, and ultimately it's on the user to manage.
