### ISSUE TITLE
Add a way to download the database without trying to import it

### ISSUE THREAD

**Issue by joestewart** [acquia/cli#596]
I would find it useful to just download the latest backup for an Acquia Cloud environment. Does this capability exist? If not, file as a feature request.

thanks,

Joe

**Comment by anavarre** [comment]
Hey @joestewart - You're in luck, it does. Try `acli pull:db --on-demand`

The help command (`acli pull:db --help`), returns the following:

>   -od, --on-demand      Force creation of an on-demand backup. This takes much longer than using an existing backup (when one is available)

**Comment by grasmash** [comment]
Not certain from the request whether it is to download a back up file or to import a back up into the local database. The example above does the latter. We don’t have a command that simply downloads without the import.

**Comment by joestewart** [comment]
Simple download without import.

The Cloud Next documentation suggests to use Acquia CLI for this purpose:

"Database backups are no longer available in SSH sessions. You can use Acquia CLI, the Cloud Platform user interface, or Cloud API v2 for database backup retrieval."
https://docs.acquia.com/cloud-platform/cloud-next/

However using the API is much more cumbersome to get the list of backups, the ID, download link, etc.

**Comment by anavarre** [comment]
> Simple download without import.

So you should be good with `acli pull:db` (latest daily backup) or `acli pull:db --on-demand` (to create an on-demand backup and pull it).

**Comment by joestewart** [comment]
Both of those attempt to connect locally and import as well don't they?

Mark as a feature request if as Grasmash said "We don’t have a command that simply downloads without the import."

**Comment by anavarre** [comment]
I've clarified the title so we capture the request which is to only download without importing the database.

**Comment by anavarre** [comment]
Options we have:

* `acli pull:db --download` to only download without importing. Should support `--on-demand`, too
* New command, e.g. `acli db:download`

**Comment by danepowell** [comment]
Note that you can use `api:environments:database-backup-download` for this today. `acli pull:db --download` would just add the UI.

**Comment by danepowell** [comment]
Give this a whirl: https://github.com/acquia/cli/pull/603
