### ISSUE TITLE
Do not assume that multidb is multisite

### ISSUE THREAD

**Issue by grasmash** [acquia/cli#622]
E.g., I have an application with one site, default. On ACE, there are two databases: the default one and a migrate one. ACLI provides this prompt:

![image](https://user-images.githubusercontent.com/539205/129293868-cc015bb6-505a-4bf2-86ca-c37182de1e05.png)

This is wrong. It should only show 'default' since there is only one site.

**Comment by grasmash** [comment]
This is an ACN site btw. Weird that ACN creates a `migrate` directory at `"/mnt/gfs/$sitegroup.{$cloud_environment->name}/sites"`.

**Comment by anavarre** [comment]
It's something with your env/site. I'm not able to confirm the issue with my own test ACN site. Maybe some AMA leftover?

```
mytest.dev@sshd-4dc7c44v5c-rhtfc:/mnt/gfs/mytest/sites$ ls -la
total 0
drwxr-xr-x. 3 mytest.dev mytest  60 Aug 31 06:02 .
drwxr-xr-x. 7 root             root         140 Aug 31 06:02 ..
drwxr-xr-x. 4 root             root          80 Aug 31 06:02 default
```

**Comment by danepowell** [comment]
Unable to reproduce for now.
