### ISSUE TITLE
Don't include assets dir in releases

### ISSUE THREAD

**Issue by danepowell** [acquia/cli#657]
Currently we package `acli.phar` with both the `assets` directory and `var/cache/ApiCommands.cache`. This is redundant, as `ApiCommands.cache` is compiled from `assets/acquia-spec.yaml` as part of the release.

Removing the assets directory would trim a couple MB (20%) off the size of `acli.phar`.

This would require a minor change to `ApiCommandHelper::getCloudApiSpec()` to read the cache if the spec file is missing.

**Comment by grasmash** [comment]
Smart
