### ISSUE TITLE
ide:delete should list ides belonging to the current user without requiring application selection

### ISSUE THREAD

**Issue by grasmash** [acquia/cli#710]

**Comment by anavarre** [comment]
If we do this, we change the pattern we have to only execute commands against a specific app when it's passed at the command line (via its UUID or `app.stage`) or having to pick an application form the array that is presented to the user.

Also, if you have access to 3 applications and have 3 different IDEs named "test", will this not be very confusing?

**Comment by grasmash** [comment]
Or, we could name the command appropriately. `ide:list-mine` or some such.

**Comment by anavarre** [comment]
I guess I don't feel the urge to create a new command for that specifically while there's already a very good way of doing that with `acli ide:delete myapp`
