### ISSUE TITLE
1.18.0: `acli remote:aliases:download` downloads aliases into `<pwd>/drush/sites` instead of `<projectroot>/drush/sites`

### ISSUE THREAD

**Issue by rfay** [acquia/cli#721]
In 1.18.0: `acli remote:aliases:download` downloads aliases into `<pwd>/drush/sites` instead of `<projectroot>/drush/sites`

It should not download relative to current directory. 

Example: If in vendor directory

```
$ echo 9 | acli remote:aliases:download
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.

 Choose your preferred alias compatibility: [Drush 9+ / Drupal 8+ (YAML)]:
  [8] Drush 8 / Drupal 7 (PHP)
  [9] Drush 9+ / Drupal 8+ (YAML)
 >
 Please select a Cloud Platform application: [Alejandro Moreno (Employee Free)]:
  [0] Alejandro Moreno (Employee Free)
  [1] Acquia Cloud Next
 > Cloud Platform Drush aliases installed into /var/www/html/vendor/drush/sites
```

It should have downloaded into `/var/www/html/drush/sites` instead.

**Comment by danepowell** [comment]
I cannot replicate this bug on any version of ACLI from 1.17 to 1.19. Can you provide any more details about when this happens, or your development environment?

Unless you've specifically overridden it, ACLI gets the current project directory from [Symfony's kernel.project_dir](https://symfony.com/doc/current/reference/configuration/kernel.html#project-directory), which is set based on the location of composer.json. So the only contributing factor to this bug that I can think of is a missing or corrupt composer.json.

```
~/example/vendor $ acli remote:aliases:download
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.

 Choose your preferred alias compatibility: [Drush 9+ / Drupal 8+ (YAML)]:
  [8] Drush 8 / Drupal 7 (PHP)
  [9] Drush 9+ / Drupal 8+ (YAML)
 > 9

Cloud Platform Drush aliases installed into ~/example/drush/sites
```

**Comment by rfay** [comment]
This is easy to demonstrate. Note that while you mention acli 1.19, `acli self-update` gets 1.18.1 the first time you run it...

```
$ acli --version
Acquia CLI 1.18.1
```


```
$ acli remote:aliases:list

 Please select a Cloud Platform application: [Alejandro Moreno (Employee Free)]:
  [0] Alejandro Moreno (Employee Free)
  [1] Acquia Cloud Next
 > 0

+----------------------------------+-------------------+--------------------------------------------+
| Application                      | Environment Alias | Environment UUID                           |
+----------------------------------+-------------------+--------------------------------------------+
| Alejandro Moreno (Employee Free) | eeamoreno.dev     | 36120-781af1ee-359f-44a9-8944-652e50500f1b |
| Alejandro Moreno (Employee Free) | eeamoreno.prod    | 36119-781af1ee-359f-44a9-8944-652e50500f1b |
| Alejandro Moreno (Employee Free) | eeamoreno.stg     | 36121-781af1ee-359f-44a9-8944-652e50500f1b |
+----------------------------------+-------------------+--------------------------------------------+
```

```
$ acli remote:aliases:download
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.

 Choose your preferred alias compatibility: [Drush 9+ / Drupal 8+ (YAML)]:
  [8] Drush 8 / Drupal 7 (PHP)
  [9] Drush 9+ / Drupal 8+ (YAML)
 > 9

 Please select a Cloud Platform application: [Alejandro Moreno (Employee Free)]:
  [0] Alejandro Moreno (Employee Free)
  [1] Acquia Cloud Next
 > 0

Cloud Platform Drush aliases installed into /tmp/drush/sites
```


Note that the drush aliases were downloaded into the current directory. Or rather, the current directory was /tmp, and the aliases were downloaded into /tmp/drush/sites. Not the right place.

**Comment by rfay** [comment]
A side note: It would be really lovely if the options could be selected with command-line args. 

Currently, to support this version, ddev has to spit args into stdin, but that's really ugly. ddev is currently stuck on v1.14.0 because I really wasn't able to recover and get anything working after the changes in https://github.com/acquia/cli/issues/508

I'll hope to return someday and try it, but this is a key thing - it assumes interactive usage, and there should be a noninteractive technique.

**Comment by danepowell** [comment]
From your latest example, it looks like you are running acli in `/tmp`. Presumably there is not a Drupal installation at `/tmp`, so the behavior you are describing (downloading into the cwd) is the expected behavior. In fact I don't know what other behavior you _could_ expect without a Drupal root present.

Like I said previously, ACLI simply relies on Symfony to determine the Drupal root directory, which is essentially the first parent directory Symfony finds with a `composer.json` file. Can you provide a failing example where you are running the command in a Drupal installation with a proper `composer.json` file?

**Comment by rfay** [comment]
Wherever you are, it downloads into the current directory. Try it in a `tmp` directory of a drupal repo.

**Comment by danepowell** [comment]
I need access to an environment where I can reproduce this. Can you try creating an Acquia Lando environment and sharing your .lando.yml and steps to reproduce there?

> Wherever you are, it downloads into the current directory

Just to be clear, the expected behavior varies depending on whether you are in a "Drupal repo". Whether the current directory is a Drupal repo is determined by having a `composer.json` in a parent directory (possibly with Drupal-specific stuff in it, I haven't looked into Symfony Kernel's guts yet). The directory containing `composer.json` is the "repo root".

- Downloading into the repo root (not necessarily the current directory) is the expected behavior if the current directory is a Drupal repo.
- Downloading into the current directory _is_ the expected behavior if the current directory is not a Drupal repository.

> Try it in a tmp directory of a drupal repo

As I mentioned above, I've tried this in various subdirectories (`<drupal-root/vendor>`, `<drupal-root/tmp>`) and it always works as expected (downloading to the repo root).

**Comment by rfay** [comment]
I confirm that if you're inside the project directory it downloads to `<project>/drush/sites`

I think the behavior when you're outside the project directory is all wrong. Maybe it should just throw an error if it's depending on symfony?

If you think the behavior is OK as is, it's fine to close this. 

```
$ mkdir junk
rfay@eeamoreno-web:/var/www/html$ cd junk/
rfay@eeamoreno-web:/var/www/html/junk$ acli remote:aliases:download
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Would you like to share anonymous performance usage and data? (yes/no) [yes]:
 > no

Ok, no data will be collected and shared with us.
We take privacy seriously.
If you change your mind, run acli telemetry.
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.

 Choose your preferred alias compatibility: [Drush 9+ / Drupal 8+ (YAML)]:
  [8] Drush 8 / Drupal 7 (PHP)
  [9] Drush 9+ / Drupal 8+ (YAML)
 > 9

Cloud Platform Drush aliases installed into /var/www/html/drush/sites
```

**Comment by grasmash** [comment]
Throwing an exception seems reasonable. It also might be nice to add an option that allows you to specify the destination directory for the aliases.

**Comment by rfay** [comment]
If you could specify the destination directory it would help me piles because I haven't been able to recover at this point from the change that got us here in the first place. (changing from putting it into ~/.drush)
