### ISSUE TITLE
Incorrect required request parameter name for api:subscriptions:post-domain-registration endpoint

### ISSUE THREAD

**Issue by klaw772** [acquia/cli#766]
Currently as part of the acli:api:subscriptions:post-domain-registration endpoint, the 'hostname' parameter is required, as described in the Cloud API docs. However, this endpoint requires the 'domain' parameter. As a 'hostname' option exists in the CLI for this command but not 'domain', an error occurs when attempting to run this command explaining that the domain parameter is missing (see attached screenshot).
<img width="1037" alt="Screen Shot 2021-12-23 at 4 34 39 PM" src="https://user-images.githubusercontent.com/28101298/147293360-f1da3cb1-a4f6-4df6-aad1-ddd18e4c962b.png">
 A ticket has been filed to modify the API docs to show the correct parameter name as well.

**Comment by grasmash** [comment]
These command parameters are created directly from the API specification. Once the specification is updated, this will be automatically fixed.

**Comment by grasmash** [comment]
@klaw772 Did you file a corresponding Cloud API ticket for this?

**Comment by klaw772** [comment]
@grasmash yes! The fix is being held until the release freeze is over, but it is all set to be merged.

**Comment by klaw772** [comment]
@grasmash the fix for this is now live in the API spec! About how long does it take for the CLI API schema to be automatically updated?
