### ISSUE TITLE
Identify canonical source of OpenAPI spec

### ISSUE THREAD

**Issue by manarth** [acquia/cli#768]
The composer command [update-cloud-api-spec](https://github.com/acquia/cli/blob/aa105ed2e50f59cc1156a59b5e8be7039e15af38/composer.json#L145) references the GitHub repository `acquia/cx-api-spec` which either does not exist, or is not publicly available.

The repo is also referenced in [`ApiCommandHelper::getCloudApiSpec()`](https://github.com/acquia/cli/blob/aa105ed2e50f59cc1156a59b5e8be7039e15af38/src/Command/Api/ApiCommandHelper.php#L454).

There is _an_ instance of the spec in the assets folder of this repository: https://github.com/acquia/cli/blob/master/assets/acquia-spec.yaml (last updated 11 days ago).

Could you please confirm the canonical source for the spec, and update the documentation to match?

**Comment by grasmash** [comment]
That is the canonical source, but it is not a public repository.
