### ISSUE TITLE
Impossible to use remote:aliases:download in non-interactive mode

### ISSUE THREAD

**Issue by rfay** [acquia/cli#790]
Many applications have to use `acli remote:aliases:download -n`, but it seems to be impossible in current versions.

I'm trying to maintain ddev's acquia integration and update acli to current (it's been stuck at v1.14.0). 

But there seems to be no way I can get this to work in non-interactive mode:

It appears that I have to set the cloud_app_uuid: 781af1ee-359f-44a9-8944-652e50500f1b in .acquia-cli.yml before I can use noninteractive, but I can only do that by walking through the interactive version once.

```
$ acli remote:aliases:download --destination-dir $HOME/.drush -n
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.

In CommandBase.php line 790:

  Could not determine Cloud Application. Run this command interactively or us
  e `acli link` to link a Cloud Application before running non-interactively.


remote:aliases:download [--destination-dir DESTINATION-DIR]
```

If I walk through the interactive version first then the noninteractive setup can work:

```
$ acli remote:aliases:download --destination-dir $HOME/.drush
We strive to give you the best tools for development.
You can really help us improve by sharing anonymous performance and usage data.

 Would you like to share anonymous performance usage and data? (yes/no) [yes]:
 > no

Ok, no data will be collected and shared with us.
We take privacy seriously.
If you change your mind, run acli telemetry.
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.

 Choose your preferred alias compatibility: [Drush 9+ / Drupal 8+ (YAML)]:
  [8] Drush 8 / Drupal 7 (PHP)
  [9] Drush 9+ / Drupal 8+ (YAML)
 > 9

There is no Cloud Platform application linked to /var/www/html/.git.
 Would you like Acquia CLI to search for a Cloud application that matches your local git config? (yes/no) [yes]:
 >

Searching for a matching Cloud application...
Found a matching application!
 Would you like to link the Cloud application Alejandro Moreno (Employee Free) to this repository? (yes/no) [yes]:
 >


 [OK] The Cloud application Alejandro Moreno (Employee Free) has been linked to
      this repository by writing to .acquia-cli.yml in the repository root.


Cloud Platform Drush aliases installed into /home/rfay/.drush
```

```
$ acli remote:aliases:download --destination-dir $HOME/.drush -n
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.
Cloud Platform Drush aliases installed into /home/rfay/.drush
```

Is there a workaround to get this now-required file set up? Another acli command?

**Comment by grasmash** [comment]
Yes you can run `acli link [uuid]`.

**Comment by rfay** [comment]
Next question: How do you get `uuid` ? :)

**Comment by grasmash** [comment]
I'm assuming that you know which application you're building. You can grab the UUID out of Cloud UI (it's in the URL when you visit the application) or you could use the API to search for it if you know something about (like the application name). 

How do you want this to work? How would you like to tell ACLI which application to download aliases for?

**Comment by grasmash** [comment]
Knowing the alias would also be enough.

**Comment by rfay** [comment]
Here's what used to work with acli, nothing to do along those lines:

```bash
acli auth:login -n --key="${ACQUIA_API_KEY}" --secret="${ACQUIA_API_SECRET}"
acli remote:aliases:download -n >/dev/null
```

https://github.com/drud/ddev/blob/11f2eeec84f8de831d9ee5cb6b4df67ac41ff360/pkg/ddevapp/dotddev_assets/providers/acquia.yaml.example#L36-L37

**Comment by grasmash** [comment]
Somehow, ACLI needs to know _which_ application to download aliases for. There are a few ways ACLI can accomplish this:

* Read an env var
* Read an .acquia-cli.yml file
* Receive the UUID as an argument
* Receive the alias an as argument and "look up" the corresponding UUID
* Ask the user for it interactively
* Search for it based on the git URL of the current repository

If someone has it working today, they're using at least one of these methods to tell acli to identify the application.

Did one of those ways stop working as expected?

**Comment by rfay** [comment]
Until sometime after 1.14, those weren't required. With v1.14, this works in ddev's automated tests every day.

**Comment by grasmash** [comment]
My guess is that in 1.14 and earlier, we just downloaded aliases for all of your applications rather than the "current" application. Is that the behavior you want?

**Comment by grasmash** [comment]
Ok. So here's a proposal. We add an argument to like `--all` to the `remote:aliases:download` command. So you'd run `acli remote:aliases:download --all`  and it would _NOT_ ask you for the application UUID and would instead download the aliases for every application that you gave access to.

**Comment by rfay** [comment]
That would certainly get me out of where I am with the ddev acquia integration. I guess it would break people when ddev updates the acli version, but I don't see another alternative. Oh, I guess going back to the original behavior would be an option.

**Comment by grasmash** [comment]
How do you feel about dropping Drupal 7 alias support?

**Comment by rfay** [comment]
Good question. I don't have any experience with using a drupal7 site with ddev's Acquia integration. My expectation would be that it would be OK. I know it causes some pain. 

Also, it's it a drush version difference, rather than D7 vs D8/9?

**Comment by grasmash** [comment]
@rfay Can you test this change?

**Comment by rfay** [comment]
I will give it a try. Might not be today.

**Comment by rfay** [comment]
This seems to work without the --destination-dir argument but not with it:

```
$ acli remote:aliases:download --all -n
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.
Cloud Platform Drush aliases installed into /var/www/html/drush/sites
rfay@eeamoreno-web:/var/www/html$ ls drush/sites/
eeamoreno.site.yml  nexteeamoreno.site.yml
```


With `--destination-dir` it claims to work but actually does nothing.

```
$ acli remote:aliases:download --all --destination-dir $HOME/.drush -n
Drush changed how aliases are defined in Drush 9. Drush 8 aliases are PHP-based and stored in your home directory, while Drush 9+ aliases are YAML-based and stored with your project.
Cloud Platform Drush aliases installed into /home/rfay/.drush
rfay@eeamoreno-web:/var/www/html$ ls ~/.drush
```

**Comment by rfay** [comment]
@grasmash any followup on that? I'd like to get a newer version into next release of ddev.

**Comment by grasmash** [comment]
This is now passing tests and appears to work both with and without the --destination-dir option.

**Comment by rfay** [comment]
Cool, thanks. Unfortunately, I/ddev no longer have access to any Acquia account so are unable to maintain the ddev/Acquia integration. @eporama is working on it though. Thanks for working on the PR.
