### ISSUE TITLE
CLI-641: Improve cs:wizard UX

### ISSUE THREAD

**Issue by grasmash** [acquia/cli#803]
1. If the user only has access to 1 Cloud app, don't ask them to make a choice. Just default to the one option.
2. Don't ask them to choose a cloud application twice.

![image](https://user-images.githubusercontent.com/539205/151395337-ca2024bb-eef5-4f69-b8e9-8784e99a2e5d.png)

**Comment by danepowell** [comment]
I think this should no longer be an issue following https://github.com/acquia/cli/pull/814

Additionally, I don't think it would be good to skip prompts when only a single choice is available. It's a bit too magical. Confirming the target for any command is a good idea even if only a single choice is available.
