### ISSUE TITLE
CLI-663: Copy all cron tasks from one environment to another

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#824]
Use case -

- Use has one environment say X
- User is setup-ing new environment and want to setup cron jobs same as in existing (source) environment.

**Comment by anavarre** [comment]
Is this something you do with the API today? If so how?

**Comment by joshirohit100** [comment]
We do this via php script by using `/environments/{env}/crons` cloud api.

**Comment by joshirohit100** [comment]
PR - https://github.com/acquia/cli/pull/828
