### ISSUE TITLE
CLI-681: Add code studio command to add / update some pre-defined environment variables.

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#837]
Code Studio supports some default jobs for CI / CD (https://docs.acquia.com/code-studio/configuring/modifying-default-job/#enabling-or-disabling-a-default-code-studio-job)

Those jobs can be enabled/disabled via UI by settings some environment variables.

This should be done via ACLI as well and will help (I think) to remove some steps/clicks on UI :)

**Comment by joshirohit100** [comment]
PR - https://github.com/acquia/cli/pull/843

**Comment by anavarre** [comment]
Same question for you @klaw772 - Would you have someone from the Code Studio team able to help make this happen?

**Comment by danepowell** [comment]
The associated PR was closed, I'm going to close this until someone from the Code Studio team can assist.
