### ISSUE TITLE
CLI-698: Allow ACLI to bookmark a command / List bookmarked commands

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#851]
So ACLI provides many command. Example case - I need to check which branch is deployed on a given environment. To accomplish this, I need to check the ACLI for the command (could be for other cases as well). It will be difficult to remember the command if I try same (or related operation next time).

So I would suggest to have some kind of bookmark (or wallet) where I can just store some of my frequently (or obvious) used command so that I (user) don't need to search/check in the ACLI command list for a given command.

Another example - `api:environment:* command`

**Comment by anavarre** [comment]
We might not need a command for that. If you have a Mac with ZSH, you have command prediction based on what you type.
