### ISSUE TITLE
CLI-710: How do you use alternate ssh keys with ACLI?

### ISSUE THREAD

**Issue by alphex** [acquia/cli#867]
I have to use a different (not my default, id_rsa key) ssh key with acquia.

How do I use ACLI ... with a different key?

Or to inform it WHICH ssh key to use?

Are there host addresses I can use in an "IdentityFile" configuration, like?

```
Host something.acquia...
  IdentityFile ~/.ssh/myacquiakey
```

Thanks!

Specific error.

```
acli remote:drush sitename.prod uli
name.prod@sitename.ssh.devcloud.acquia-sites.com: Permission denied (publickey).
```

**Comment by grasmash** [comment]
ACLI is just running SSH. You can configure SSH for your machine with an SSH config file. See https://linuxize.com/post/using-the-ssh-config-file/

Seems like you may want to set that host to use a specific key with something like this:
```
sitename.ssh.devcloud.acquia-sites.com
    IdentityFile ~/.ssh/targaryen.key
```

The host name is right in the error message that you posted.

**Comment by joshirohit100** [comment]
I think we should add this in documentation

**Comment by grasmash** [comment]
Seems like this is really a question about how SSH works rather than ACLI.
