### ISSUE TITLE
CLI-716: Download db backup(s) from prod to non-prod environments

### ISSUE THREAD

**Issue by erinrasmussen** [acquia/cli#878]
Add a command that would allow a customer to copy the latest database backup (or backups) from production to a non-production environment.

**Comment by anavarre** [comment]
Wouldn't the expected workflow instead be to copy the DB from prod to non-prod and then grab a DB snapshot there? It reassures me to know at every point in time DB backups are related to the environment they've been triggered against, and not some dance with moving unrelated stuff over.

What's your thought on that?

**Comment by danepowell** [comment]
Isn't this solved by `env:mirror`? If you just want the database, it would be `acli env:mirror --no-code --no-files --no-config`.
