### ISSUE TITLE
CLI-743: Email commands throw PHP warnings in PHP 8

### ISSUE THREAD

**Issue by danepowell** [acquia/cli#911]
To reproduce: `./vendor/bin/phpunit tests/phpunit/src --debug --filter=email`

`Warning: Private methods cannot be final as they are never overridden by other classes in /Users/dane.powell/src/acquia/cli/vendor/marc-mabe/php-enum/src/Enum.php on line 73`

Upstream issue: https://github.com/LTD-Beget/dns-zone-configurator/issues/37

cc @klaw772 since I think you contributed these commands

**Comment by grasmash** [comment]
This is resolved in 2.x.
