### ISSUE TITLE
Failing to download drush aliases

### ISSUE THREAD

**Issue by lnunesbr** [acquia/cli#96]
Using drush 8:

```
~$ drush --version
 Drush Version   :  8.3.1-dev
```

acli latest release

```
~$ acli --version
acli v1.0.0-beta1
```

acli is properly configured to acquia as I can retrieve **api:applications:list**

```
~$ acli api:applications:list
[
    {
        "id": 9999,
        "uuid": "000bXXXXXXXXXX",
        "name": "XXXXXXX",
        "hosting": {
            "type": "ace",
            "id": "prod:XXXXXX"
        },
        "subscription": {
            "uuid": "000XXXXX",
            "name": "XXXXXXXX"
        },
[..snip..]
```

But drush aliases download command `api:accounts:drush-aliases` is failing:

```
~$ acli api:accounts:drush-aliases 8

In Client.php line 110:

  Only Drush 8 and 9 are supported.


api:accounts:drush-aliases [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> <version>
```

**Comment by grasmash** [comment]
Just FYI, there's a separate `remote:aliases:download` command to download aliases and a `remote:drush` command to allow you to run drush commands remotely _without_ needing to download drush aliases.

**Comment by grasmash** [comment]
Anyway, the actual bug comes from a namespace collision. All Symfony commands have a `--version` option. Our API command confuses that with the Drush 8 `version` argument. Will fix.

**Comment by lnunesbr** [comment]
I wasn't familiar with those `remote:` commands... will give it a try.

**Comment by grasmash** [comment]
Fixed by https://github.com/acquia/cli/pull/97
