### ISSUE TITLE
CLI-757: Update PHP version requirements in the documentation

### ISSUE THREAD

**Issue by fractile81** [acquia/cli#974]
Since v1.30.1 changed the PHP requirement to PHP 8, update relevant documentation to indicate as such.  Unless this is unintended for v1 releases since it's breaking BC with a patch release.

See https://docs.acquia.com/acquia-cli/install/, which still indicates only PHP 7.4 is needed.

**Comment by grasmash** [comment]
I think 2.0.0 was intended for PHP 8, not 1.30.1. We may need to release 1.30.2 as a hot fix to address that.

**Comment by anavarre** [comment]
Interestingly I see:

> * Revert "Fixes https://github.com/acquia/cli/issues/782: Update to Symfony 6 and require PHP ^8" @grasmash (https://github.com/acquia/cli/pull/928)
> * Fixes https://github.com/acquia/cli/issues/782: Update to Symfony 6 and require PHP ^8 @grasmash (https://github.com/acquia/cli/pull/927)

So understand we should have had this reverted as intended.

**Comment by grasmash** [comment]
Looks like 1.30.1 supports both PHP 7.4 and 8:
https://github.com/acquia/cli/blob/1.30.1/composer.json#L14

**Comment by fractile81** [comment]
Using Lando, it appears I had it set to use "latest", which I'm guessing pulled the latest v2 alpha.  I couldn't find out the version because it kept throwing a PHP v8 error.

**Comment by grasmash** [comment]
Ah, I see. That's an unintended side effect of releasing 2.0.0-alpha1. Our `acli update` command only pulls in stable releases. I guess land simply uses this URL: https://github.com/acquia/cli/releases/latest/download/acli.phar

**Comment by fractile81** [comment]
I'll close this issue due to the confusion on my end, then.  Apologies for that.

**Comment by grasmash** [comment]
For posterity, you can configure the ACLI version for Lando like so: https://docs.lando.dev/acquia/config.html#configuration
```
recipe: acquia
config:
  acli_version: "1.30.1"
```
